/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PharmacistRole;

import DataStore.ItemTuple;
import EcoSystem.EcoSystem;
import Medicine.Medicine;
import Pharmacy.Pharmacy;
import java.awt.CardLayout;
import java.awt.Component;
import java.time.LocalDate;
import javax.lang.model.SourceVersion;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sravya
 */
public class AddMedicineStockJPanel extends javax.swing.JPanel {

    private JPanel workArea;
    private Pharmacy pharmacy;
    private EcoSystem ecoSystem;

    public AddMedicineStockJPanel(JPanel wa, Pharmacy ph, EcoSystem ecoSystem){
        initComponents();
        workArea = wa;
        pharmacy = ph;
        ecoSystem = ecoSystem;
        populatecmbMedicineId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddMedicineStock = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAddMedicineStock = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cmbMedicineId = new javax.swing.JComboBox<>();
        spnAddMedicineQuantity = new javax.swing.JSpinner();

        lblAddMedicineStock.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblAddMedicineStock.setText("Add Medicine Stock");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Medicine:");

        btnAddMedicineStock.setBackground(new java.awt.Color(204, 255, 204));
        btnAddMedicineStock.setText("Add ");
        btnAddMedicineStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMedicineStockActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Quantity:");

        cmbMedicineId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMedicineIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(cmbMedicineId, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(spnAddMedicineQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(265, 265, 265))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnBack)
                        .addGap(55, 55, 55)
                        .addComponent(lblAddMedicineStock))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(btnAddMedicineStock)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(lblAddMedicineStock))
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMedicineId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnAddMedicineQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnAddMedicineStock)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMedicineStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMedicineStockActionPerformed

        int quantity = 0;
        try {
            if(spnAddMedicineQuantity.getValue()!=null){
                quantity = (Integer)spnAddMedicineQuantity.getValue();
                if (quantity <= 0) {
                    JOptionPane.showMessageDialog(this, "Quantity must always be positive.");
                    return;
                }
                Medicine medicine = (Medicine) cmbMedicineId.getSelectedItem();
                pharmacy.addMedicineStock(medicine, quantity);
            } else{
                JOptionPane.showMessageDialog(this, "Please enter a valid quantity.");
                return;
            }
        } catch (Exception e){JOptionPane.showMessageDialog(this, "Please enter all details correctly");
            return;
        }

        JOptionPane.showMessageDialog(this, "Medicine added!", "Info", JOptionPane.INFORMATION_MESSAGE);
        spnAddMedicineQuantity.setValue(0);
        populatecmbMedicineId();
    }//GEN-LAST:event_btnAddMedicineStockActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        workArea.remove(this);
        Component[] componentArray = workArea.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageMedicineStockJPanel manageMedicineCatalogJPanel = (ManageMedicineStockJPanel) component;
        manageMedicineCatalogJPanel.refreshTable();
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    public void populatecmbMedicineId() {
        cmbMedicineId.removeAllItems();
        for(Medicine med : ecoSystem.getMedicineDirectory().medicineCatalogMap.getAllValues()) {
            cmbMedicineId.addItem(med);
        }
    }

    
    private void cmbMedicineIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMedicineIdActionPerformed
        // TODO add your handling code here:
        populatecmbMedicineId();
    }//GEN-LAST:event_cmbMedicineIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMedicineStock;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<Medicine> cmbMedicineId;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblAddMedicineStock;
    private javax.swing.JSpinner spnAddMedicineQuantity;
    // End of variables declaration//GEN-END:variables

   
}
