/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.PharmacistRole;

import DataStore.ItemTuple;
import EcoSystem.EcoSystem;
import Medicine.Medicine;
import Enterprise.PharmacyEnterprise;
import Utils.ConsoleLogger;
import java.awt.CardLayout;
import java.util.Map;
import java.util.Map.Entry;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sravya
 */
public class ManageMedicineStockJPanel extends javax.swing.JPanel {

    private JPanel workArea;
    private PharmacyEnterprise pharmacy;
    private EcoSystem ecoSystem;
    
    ConsoleLogger log = ConsoleLogger.getLogger();
    
    public ManageMedicineStockJPanel(JPanel workArea, PharmacyEnterprise pharmacy, EcoSystem ecoSystem) {
        initComponents();
        this.workArea = workArea;
        this.pharmacy = pharmacy;
        this.ecoSystem = ecoSystem;
        lblPharmacy.setText("Pharmacy: " + pharmacy.getEnterpriseName());
        refreshTable();
    }
    
    public void refreshTable() {

        DefaultTableModel model = (DefaultTableModel) tblMedicineCatalog.getModel();
        model.setRowCount(0);

        Map<Medicine, Integer> stock = pharmacy.getMedicineStockMap();
        if (stock == null || stock.isEmpty()) {
            log.error("Medicine stock is empty");
            return;
        }
        
        for (Entry<Medicine, Integer> tup : stock.entrySet()) {
            Object row[] = new Object[4];
            row[0] = tup.getKey().getMedicineId();
            row[1] = tup.getKey().getMedicineName();
            row[2] = tup.getKey().getPrice();
            row[3] = tup.getValue();
            model.addRow(row);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMedicineCatalog = new javax.swing.JTable();
        lblPharmacy = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnAddStock = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblMedicineCatalog.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblMedicineCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine ID", "Medicine Name", "Price", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMedicineCatalog);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 159, 960, 290));

        lblPharmacy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPharmacy.setText("Medicine Details:");
        add(lblPharmacy, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 170, -1));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setText("Manage Medicine Stock");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setBorderPainted(false);
        btnDelete.setContentAreaFilled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 110, 30));

        btnBack.setText("Back");
        btnBack.setContentAreaFilled(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 30, 40));

        btnAddStock.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnAddStock.setText("Add Stock");
        btnAddStock.setContentAreaFilled(false);
        btnAddStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStockActionPerformed(evt);
            }
        });
        add(btnAddStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 120, -1));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 1100, 850));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        int selectedRowIndex = tblMedicineCatalog.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Medicine med = (Medicine) tblMedicineCatalog.getValueAt(selectedRowIndex, 0);
        ecoSystem.getMedicineDirectory().deleteMedicine(med);
        refreshTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddMedicineStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMedicineStockActionPerformed


    }//GEN-LAST:event_btnAddMedicineStockActionPerformed

    private void btnAddStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStockActionPerformed
        // TODO add your handling code here:
        AddMedicineStockJPanel amsjp = new AddMedicineStockJPanel(workArea, pharmacy, ecoSystem);
        workArea.add("AddMedicineStockJPanel", amsjp);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnAddStockActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStock;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPharmacy;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblMedicineCatalog;
    // End of variables declaration//GEN-END:variables
}
