/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIPatientDoctorInsuranceProvider;

import EcoSystem.EcoSystem;
import Laboratory.LaboratoryAssistant;
import Laboratory.LaboratoryTest;
import Laboratory.LaboratoryTest.TestType;
import Laboratory.LaboratoryTestReport;
import Patient.Patient;
import Utils.GraphPlotterUtils;
import Utils.NextScreen;
import java.awt.Color;
import static javax.swing.GroupLayout.Alignment.values;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Ankur Bywar
 */
public class LaboratoryTestPageJPanel extends javax.swing.JPanel implements NextScreen {
    JPanel workAreaPanel;
    LaboratoryTestReport labTestReport;
    JPanel backPage;
    
    LaboratoryTest labTestResult;
    /**
     * Creates new form ViewMedicalLabTestResultJPanel
     */
    public LaboratoryTestPageJPanel(JPanel workAreaPanel, LaboratoryTestReport labTestReport, JPanel backPage) {
        initComponents();
        this.setSize(1100,850);
        this.workAreaPanel = workAreaPanel;
        this.labTestReport = labTestReport;
        this.backPage = backPage;
        labTestResult = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        defaultCategoryDataset1 = new org.jfree.data.category.DefaultCategoryDataset();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jTextFieldVitaminB12 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldHemoglobin = new javax.swing.JTextField();
        jTextFieldThyroid = new javax.swing.JTextField();
        jTextFieldVitaminD = new javax.swing.JTextField();
        jTextFieldBloodSugar = new javax.swing.JTextField();
        btnLabTestsSave = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnCompleteLabTest = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextLabTestCost = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnShowTrend = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setText("Laboratory Test Page");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 15, 255, 31));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/back.png"))); // NOI18N
        btnBack.setContentAreaFilled(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 15, -1, -1));

        jTextFieldVitaminB12.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jTextFieldVitaminB12.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextFieldVitaminB12, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 209, 143, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setText("Haemoglobin");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 106, -1, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setText("Thyroid");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 138, 60, 25));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel4.setText("Vitamin D");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 169, -1, 25));

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel5.setText("Blood Sugar");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 237, -1, 25));

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel6.setText("Vitamin B12");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 206, 82, 25));

        jTextFieldHemoglobin.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jTextFieldHemoglobin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextFieldHemoglobin, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 106, 143, -1));

        jTextFieldThyroid.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jTextFieldThyroid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextFieldThyroid, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 141, 143, -1));

        jTextFieldVitaminD.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jTextFieldVitaminD.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextFieldVitaminD, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 172, 143, -1));

        jTextFieldBloodSugar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jTextFieldBloodSugar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextFieldBloodSugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 240, 143, -1));

        btnLabTestsSave.setBackground(new java.awt.Color(255, 255, 255));
        btnLabTestsSave.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnLabTestsSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/save.png"))); // NOI18N
        btnLabTestsSave.setText("Save");
        btnLabTestsSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLabTestsSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnLabTestsSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 312, 103, -1));

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel7.setText("Add patient details (name, age, etc.) and Doctor details.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 69, -1, -1));

        btnCompleteLabTest.setBackground(new java.awt.Color(255, 255, 255));
        btnCompleteLabTest.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnCompleteLabTest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/icons8-test-tube-30.png"))); // NOI18N
        btnCompleteLabTest.setText("Finalize Lab Test");
        btnCompleteLabTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteLabTestActionPerformed(evt);
            }
        });
        jPanel1.add(btnCompleteLabTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 312, 187, -1));

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel8.setText("Lab Test Cost");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 275, 93, 25));

        jTextLabTestCost.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jTextLabTestCost.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextLabTestCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 278, 143, -1));

        jPanel2.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        btnShowTrend.setBackground(new java.awt.Color(255, 255, 255));
        btnShowTrend.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnShowTrend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/icons8-graph-report-30.png"))); // NOI18N
        btnShowTrend.setText("Show Trends");
        btnShowTrend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowTrendActionPerformed(evt);
            }
        });
        jPanel1.add(btnShowTrend, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 312, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/polygonal-bg1100X850.jpg"))); // NOI18N
        jLabel9.setToolTipText("");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1100, 850));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        nextScreen(workAreaPanel, backPage, "LabAssistantHomePage");
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnLabTestsSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLabTestsSaveActionPerformed
        // TODO add your handling code here:
        
        double bloodSugar = Double.parseDouble(jTextFieldBloodSugar.getText());
        double hemoglobin = Double.parseDouble(jTextFieldHemoglobin.getText());
        double thyroid = Double.parseDouble(jTextFieldThyroid.getText());
        double vitaminD = Double.parseDouble(jTextFieldVitaminD.getText());
        double vitaminB12 = Double.parseDouble(jTextFieldVitaminB12.getText());
        double labTestCost = Double.parseDouble(jTextLabTestCost.getText());
        
        labTestResult = new LaboratoryTest();
        labTestResult.add(TestType.BLOOD_SUGAR, bloodSugar);
        labTestResult.add(TestType.HEMOGLOBIN, hemoglobin);
        labTestResult.add(TestType.THYROID, thyroid);
        labTestResult.add(TestType.VITAMIN_D, vitaminD);
        labTestResult.add(TestType.VITAMIN_B12, vitaminB12);
        labTestReport.setLabTestCost(labTestCost);
    }//GEN-LAST:event_btnLabTestsSaveActionPerformed

    private void btnCompleteLabTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteLabTestActionPerformed
        // TODO add your handling code here:
        if (labTestResult == null) {
           JOptionPane.showMessageDialog(null,"Please enter lab test results or press back to return.", "Warning", JOptionPane.WARNING_MESSAGE );
           return;
        }

        labTestReport.setLaboratoryTestResult(labTestResult);
        LaboratoryAssistant labAssistant = labTestReport.getLabAssistant();
        labAssistant.finishLabTest(labTestReport);
        ((LaboratoryAssistantHomePagePanel)backPage).reload();
        
        btnLabTestsSave.setEnabled(false);
        btnCompleteLabTest.setEnabled(false);
        JOptionPane.showMessageDialog(null,"Lab Tests Results Saved.", "Information", JOptionPane.INFORMATION_MESSAGE );
    }//GEN-LAST:event_btnCompleteLabTestActionPerformed

    private void btnShowTrendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowTrendActionPerformed
        // TODO add your handling code here:
       String Hemoglobin = jTextFieldHemoglobin.getText();
       String Thyroid = jTextFieldThyroid.getText();
       String VitaminD = jTextFieldVitaminD.getText();
       String VitaminB12 = jTextFieldVitaminB12.getText();
       String BloodSugar = jTextFieldBloodSugar.getText();
       DefaultCategoryDataset dcd = new DefaultCategoryDataset();
       GraphPlotterUtils graphPlotterUtils = new GraphPlotterUtils();
       dcd.setValue(new Integer(Hemoglobin), "values", "hemoglobin");
       dcd.setValue(new Integer(Thyroid), "values", "thyroid");
       dcd.setValue(new Integer(VitaminD), "values", "VitaminD");
       dcd.setValue(new Integer(VitaminB12), "values", "VitaminB12");
       dcd.setValue(new Integer(BloodSugar), "values", "BloodSugar");
       graphPlotterUtils.createBarChart3D("lab tests", "Ranges", "All lab tests trends", "lab test", dcd, jPanel2);
       //graphPlotterUtils.addToDataSet(values, VitaminD, dcd);
       
       
       
       
   
     
         
//        DefaultCategoryDataset dcd = new DefaultCategoryDataset();
//       
//        dcd.setValue(new Integer(weight), "values" , "weight" );
//        dcd.setValue(new Integer(lowBp) , "values" , "lowBp");
//        dcd.setValue(new Integer(HighBp) , "values" , "highBp");
//        dcd.setValue(new Integer(respiratoryRate) , "values" , "respiratoryRate");
//        dcd.setValue(new Integer(heartRate) , "values" , "heatrate");
//        dcd.setValue(new Integer(respiratoryRate) , "values" , "respiratoryRate");
//       
//        JFreeChart jchart = ChartFactory.createBarChart3D("Record Vitals", "Vital sign", "Ranges", dcd, PlotOrientation.VERTICAL, true, true, false);
//        CategoryPlot plot = jchart.getCategoryPlot();
//        plot.setRangeGridlinePaint(Color.black);
//        ChartFrame cf = new ChartFrame("Vital sign", jchart, true);
//        cf.setVisible(true);
//        cf.setSize(500, 400);
//        ChartPanel cp = new ChartPanel(jchart);
//        jPanel2.removeAll();
//        jPanel2.add(cp);
//        jPanel2.updateUI();
        
    }//GEN-LAST:event_btnShowTrendActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCompleteLabTest;
    private javax.swing.JButton btnLabTestsSave;
    private javax.swing.JButton btnShowTrend;
    private org.jfree.data.category.DefaultCategoryDataset defaultCategoryDataset1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldBloodSugar;
    private javax.swing.JTextField jTextFieldHemoglobin;
    private javax.swing.JTextField jTextFieldThyroid;
    private javax.swing.JTextField jTextFieldVitaminB12;
    private javax.swing.JTextField jTextFieldVitaminD;
    private javax.swing.JTextField jTextLabTestCost;
    // End of variables declaration//GEN-END:variables
}
