/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIPatientDoctorInsuranceProvider;

import EcoSystem.EcoSystem;
import Laboratory.LaboratoryTestReport;
import Medicine.Medicine;
import Patient.Patient;
import Prescription.Dosage;
import Prescription.Prescription;
import Utils.ConsoleLogger;
import Utils.NextScreen;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mrs.katey
 */
public class PatientViewPrescriptionJPanel extends javax.swing.JPanel implements NextScreen {

    JPanel workAreaPanel;
    EcoSystem ecoSystem;
    JPanel backPage;
    Patient patient;
    
    ConsoleLogger log = ConsoleLogger.getLogger();
    
    /**
     * Creates new form PatientViewPrescriptionJPanel
     */
    public PatientViewPrescriptionJPanel(JPanel workAreaPanel, EcoSystem ecoSystem, Patient patient, JPanel backPage) {
        initComponents();
        this.workAreaPanel = workAreaPanel;
        this.ecoSystem = ecoSystem;
        this.backPage = backPage;
        this.patient = patient;
        
        populatePrescriptionDetailsTable(patient.getLatestMedicinePrescription());
        populatePrescriptionHistoryTable();
    }
    
    void populatePrescriptionDetailsTable(Prescription prescription) {
        DefaultTableModel  model = (DefaultTableModel) tblSinglePrescriptionDetails.getModel();
        model.setRowCount(0);
        
        if (prescription == null) {
            log.debug("No prescription found for patient: " + patient.getUserAccount().getUsername());
            return;
        }
        
        Map<Medicine, Dosage> prescriptionMap = prescription.getPrescriptionMap().getIntermalMap();
        for (Map.Entry<Medicine, Dosage> entry : prescriptionMap.entrySet()) {
            Object row[] = new Object[3];
            Medicine medicine = entry.getKey();
            Dosage dosage = entry.getValue();
            row[0] = medicine.getMedicineName();
            row[1] = dosage.getMedicineDosage();
            row[2] = dosage.getDosageTimingDetails();
            model.addRow(row);
        }
        
        jLabelPrescriptionTitlePlaceHolder.setText("Latest prescription: Date " + prescription.getPrescriptionDate() + 
                ", Referred by doctor " + prescription.getAppointment().getDoctor().getPersonDetails().getFullName());
    }
    
    void populatePrescriptionHistoryTable() {
        DefaultTableModel  model = (DefaultTableModel) tblPrescriptionHistory.getModel();
        model.setRowCount(0);
        
        List<Prescription> prescriptionList = patient.getPrescriptionsList();
        if (prescriptionList == null || prescriptionList.isEmpty()) {
            log.debug("No previous prescriptions found for patient: " + patient.getUserAccount().getUsername());
            return;
        }
        
        for (Prescription prescription : prescriptionList) {
            Object row[] = new Object[3];
            row[0] = prescription.getAppointment().getId();
            row[1] = prescription.getPrescriptionDate();
            row[2] = prescription.getAppointment().getDoctor().getPersonDetails().getFullName();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSinglePrescriptionDetails = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblPrescriptionHistory = new javax.swing.JTable();
        btnShowDetailsOfPrescription = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelPrescriptionTitlePlaceHolder = new javax.swing.JLabel();
        btnShowCurrentPrescription1 = new javax.swing.JButton();
        jBtnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 664, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 641, Short.MAX_VALUE)
        );

        jLabel1.setText("Medicine Perscription Details");

        tblSinglePrescriptionDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Medicine Name", "Dose", "Timing"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblSinglePrescriptionDetails);

        tblPrescriptionHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Prescription Date", "Referred by Doctor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblPrescriptionHistory);

        btnShowDetailsOfPrescription.setText("Show details of the selected prescription");
        btnShowDetailsOfPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowDetailsOfPrescriptionActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Prescription History");

        jLabelPrescriptionTitlePlaceHolder.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelPrescriptionTitlePlaceHolder.setText("Prescription from date <DATE>");

        btnShowCurrentPrescription1.setText("Show most recent prescription");
        btnShowCurrentPrescription1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowCurrentPrescription1ActionPerformed(evt);
            }
        });

        jBtnBack.setText("Back");
        jBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("My Current Medicine Prescription");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jBtnBack)
                        .addGap(175, 175, 175)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPrescriptionTitlePlaceHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(btnShowCurrentPrescription1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(btnShowDetailsOfPrescription, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(226, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jBtnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabelPrescriptionTitlePlaceHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnShowCurrentPrescription1)
                .addGap(40, 40, 40)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnShowDetailsOfPrescription)
                .addGap(101, 101, 101))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowDetailsOfPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowDetailsOfPrescriptionActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblPrescriptionHistory.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Selected row prescription history list");
            return;
        }
        
        int appointmentId = (Integer)tblPrescriptionHistory.getModel().getValueAt(selectedRow, 0);
        Prescription selectedPrescription = ecoSystem.getPrescriptionDirectory().getPrescription(appointmentId);
        if (selectedPrescription == null) {
            JOptionPane.showMessageDialog(null, "No prescription found for appointment id: " + appointmentId);
            return;
        }
        
        populatePrescriptionDetailsTable(selectedPrescription);
    }//GEN-LAST:event_btnShowDetailsOfPrescriptionActionPerformed

    private void btnShowCurrentPrescription1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowCurrentPrescription1ActionPerformed
        // TODO add your handling code here:
        populatePrescriptionDetailsTable(patient.getLatestMedicinePrescription());
    }//GEN-LAST:event_btnShowCurrentPrescription1ActionPerformed

    private void jBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackActionPerformed
        // TODO add your handling code here:
        nextScreen(workAreaPanel, backPage, "PatientHomePage");
    }//GEN-LAST:event_jBtnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShowCurrentPrescription1;
    private javax.swing.JButton btnShowDetailsOfPrescription;
    private javax.swing.JButton jBtnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelPrescriptionTitlePlaceHolder;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tblPrescriptionHistory;
    private javax.swing.JTable tblSinglePrescriptionDetails;
    // End of variables declaration//GEN-END:variables
}
