/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIPatientDoctorInsuranceProvider;

import EcoSystem.EcoSystem;
import Laboratory.LaboratoryTestReport;
import Medicine.Medicine;
import Patient.Patient;
import Prescription.Dosage;
import Prescription.Prescription;
import Utils.ConsoleLogger;
import Utils.FieldsDecorator;
import Utils.NextScreen;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mrs.katey
 */
public class PatientViewPrescriptionJPanel extends javax.swing.JPanel implements NextScreen {

    JPanel workAreaPanel;
    EcoSystem ecoSystem;
    JPanel backPage;
    Patient patient;
    
    ConsoleLogger log = ConsoleLogger.getLogger();
    
    /**
     * Creates new form PatientViewPrescriptionJPanel
     */
    public PatientViewPrescriptionJPanel(JPanel workAreaPanel, EcoSystem ecoSystem, Patient patient, JPanel backPage) {
        initComponents();
        this.setSize(1100,850);
        this.workAreaPanel = workAreaPanel;
        this.ecoSystem = ecoSystem;
        this.backPage = backPage;
        this.patient = patient;
        
        FieldsDecorator.decorateTable(tblSinglePrescriptionDetails);
        FieldsDecorator.decorateTable(tblPrescriptionHistory);
        populatePrescriptionDetailsTable(patient.getLatestMedicinePrescription());
        populatePrescriptionHistoryTable();
    }
    
    void populatePrescriptionDetailsTable(Prescription prescription) {
        DefaultTableModel  model = (DefaultTableModel) tblSinglePrescriptionDetails.getModel();
        model.setRowCount(0);
        
        if (prescription == null) {
            log.debug("No prescription found for patient: " + patient.getUserAccount().getUsername());
            return;
        }
        
        Map<Medicine, Dosage> prescriptionMap = prescription.getPrescriptionMap().getIntermalMap();
        for (Map.Entry<Medicine, Dosage> entry : prescriptionMap.entrySet()) {
            Object row[] = new Object[3];
            Medicine medicine = entry.getKey();
            Dosage dosage = entry.getValue();
            row[0] = medicine.getMedicineName();
            row[1] = dosage.getMedicineDosage();
            row[2] = dosage.getDosageTimingDetails();
            model.addRow(row);
        }
        
        jLabelPrescriptionTitlePlaceHolder.setText("Latest prescription: Date " + prescription.getPrescriptionDate() + 
                ", Referred by doctor " + prescription.getAppointment().getDoctor().getPersonDetails().getFullName());
    }
    
    void populatePrescriptionHistoryTable() {
        DefaultTableModel  model = (DefaultTableModel) tblPrescriptionHistory.getModel();
        model.setRowCount(0);
        
        List<Prescription> prescriptionList = patient.getPrescriptionsList();
        if (prescriptionList == null || prescriptionList.isEmpty()) {
            log.debug("No previous prescriptions found for patient: " + patient.getUserAccount().getUsername());
            return;
        }
        
        for (Prescription prescription : prescriptionList) {
            Object row[] = new Object[3];
            row[0] = prescription.getPrescriptionDate();
            row[1] = prescription.getAppointment().getDoctor().getPersonDetails().getFullName();
            row[2] = prescription.getAppointment().getId();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSinglePrescriptionDetails = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblPrescriptionHistory = new javax.swing.JTable();
        btnShowDetailsOfPrescription = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelPrescriptionTitlePlaceHolder = new javax.swing.JLabel();
        btnShowCurrentPrescription1 = new javax.swing.JButton();
        jBtnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 664, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 641, Short.MAX_VALUE)
        );

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setText("Medicine Prescription Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 27, 520, 31));

        tblSinglePrescriptionDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine Name", "Dose", "Timing"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblSinglePrescriptionDetails);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 149, 820, 159));

        tblPrescriptionHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Prescription Date", "Referred by Doctor", "Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblPrescriptionHistory);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 449, 820, 148));

        btnShowDetailsOfPrescription.setBackground(new java.awt.Color(255, 255, 255));
        btnShowDetailsOfPrescription.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnShowDetailsOfPrescription.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/view_notes.png"))); // NOI18N
        btnShowDetailsOfPrescription.setText("Show details of the selected prescription");
        btnShowDetailsOfPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowDetailsOfPrescriptionActionPerformed(evt);
            }
        });
        add(btnShowDetailsOfPrescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 615, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Prescription History");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 227, 31));

        jLabelPrescriptionTitlePlaceHolder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPrescriptionTitlePlaceHolder.setText("Prescription from date <DATE>");
        add(jLabelPrescriptionTitlePlaceHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 580, 31));

        btnShowCurrentPrescription1.setBackground(new java.awt.Color(255, 255, 255));
        btnShowCurrentPrescription1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnShowCurrentPrescription1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/icons8-submit-resume-30.png"))); // NOI18N
        btnShowCurrentPrescription1.setText("Show most recent prescription");
        btnShowCurrentPrescription1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowCurrentPrescription1ActionPerformed(evt);
            }
        });
        add(btnShowCurrentPrescription1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        jBtnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/back.png"))); // NOI18N
        jBtnBack.setContentAreaFilled(false);
        jBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackActionPerformed(evt);
            }
        });
        add(jBtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 19, 48, 39));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("My Current Medicine Prescription");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 113, 340, 31));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/polygonal-bg1100X850.jpg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 1100, 850));
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowDetailsOfPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowDetailsOfPrescriptionActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblPrescriptionHistory.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Selected row prescription history list");
            return;
        }
        
        long appointmentId = (Long)tblPrescriptionHistory.getModel().getValueAt(selectedRow, 2);
        Prescription selectedPrescription = ecoSystem.getPrescriptionDirectory().getPrescription(appointmentId);
        if (selectedPrescription == null) {
            JOptionPane.showMessageDialog(null, "No prescription found for appointment id: " + appointmentId);
            return;
        }
        
        populatePrescriptionDetailsTable(selectedPrescription);
    }//GEN-LAST:event_btnShowDetailsOfPrescriptionActionPerformed

    private void btnShowCurrentPrescription1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowCurrentPrescription1ActionPerformed
        // TODO add your handling code here:
        populatePrescriptionDetailsTable(patient.getLatestMedicinePrescription());
    }//GEN-LAST:event_btnShowCurrentPrescription1ActionPerformed

    private void jBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackActionPerformed
        // TODO add your handling code here:
        nextScreen(workAreaPanel, backPage, "PatientHomePage");
    }//GEN-LAST:event_jBtnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShowCurrentPrescription1;
    private javax.swing.JButton btnShowDetailsOfPrescription;
    private javax.swing.JButton jBtnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelPrescriptionTitlePlaceHolder;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tblPrescriptionHistory;
    private javax.swing.JTable tblSinglePrescriptionDetails;
    // End of variables declaration//GEN-END:variables
}
