/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SysAdminUI;

import Counselor.Counselor;
import DataStore.CredentialsManager;
import DataStore.GlobalUserDirectory;
import DeliveryMan.DeliveryMan;
import Dietitian.Dietitian;
import Doctor.Doctor;
import EcoSystem.EcoSystem;
import Enterprise.Enterprise;
import Enterprise.EnterpriseType;
import Enterprise.HealthManagementAppEnterprise;
import Enterprise.HospitalEnterprise;
import Enterprise.InsuranceCompanyEnterprise;
import Enterprise.MentalWellnessEnterprise;
import Enterprise.PhysicalWellnessEnterprise;
import FitnessTrainer.FitnessTrainer;
import Insurance.InsuranceProviderRepresentative;
import Laboratory.LaboratoryAssistant;
import Organization.Organization;
import Organization.OrganizationType;
import Patient.Patient;
import Personnel.Address;
import Personnel.Person;
import Personnel.PersonDetails;
import Personnel.PersonDetails.Gender;
import Personnel.Role;
import Personnel.UserAccount;
import Pharmacy.Pharmacist;
import Utils.ConsoleLogger;
import Utils.FieldsValidator;
import Utils.NextScreen;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.commons.lang.StringUtils;
import org.apache.commons.validator.routines.EmailValidator;

/**
 *
 * @author mrs.katey
 */
public class CreateRolesJPanel extends javax.swing.JPanel implements NextScreen {
   JPanel WorkArea;
   EcoSystem system;
   Person person;
   ImageIcon logoImage;
   JPanel backPage;
   private final JFileChooser fileChooser = new JFileChooser();
   ConsoleLogger log = ConsoleLogger.getLogger();
   
    /**
     * Creates new form ManageRoles
     */
    public CreateRolesJPanel(JPanel WorkArea, EcoSystem system, JPanel backPage) {
        initComponents();
        this.setSize(1100, 850);
        this.WorkArea = WorkArea;
        this.system = system;
        this.person = person;
        this.backPage = backPage;
        GlobalUserDirectory globalUserDirectory;
        FileFilter jpegFilter = new FileNameExtensionFilter("JPEG file" , "jpg" , "jpeg");
        FileFilter pngFilter = new FileNameExtensionFilter("PNG file" , "png" , "png");
        
        txtDobDateChooser.setMaxSelectableDate(Date.from(Instant.now().minusMillis(86400000)));
        
        fileChooser.addChoosableFileFilter(jpegFilter);
        fileChooser.addChoosableFileFilter(pngFilter);
        fileChooser.setFileFilter(pngFilter);
        populateEnterpriseCombo();
        populateOrganizationCombo(null);
        disableAllRolesRadioButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        btnAttach = new javax.swing.JButton();
        btnRemove1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblDob = new javax.swing.JLabel();
        txtDobDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        lblAddrStreet = new javax.swing.JLabel();
        txtAddressStreet = new javax.swing.JTextField();
        lblAddrCity = new javax.swing.JLabel();
        txtAddressCity = new javax.swing.JTextField();
        lblAddrZip = new javax.swing.JLabel();
        txtAddressZip = new javax.swing.JTextField();
        jComboBoxAddrState = new javax.swing.JComboBox<>();
        lblAddrState = new javax.swing.JLabel();
        lblAddrCountry = new javax.swing.JLabel();
        txtAddressCountry = new javax.swing.JTextField();
        jUsernameLabel = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jPasswordLabel = new javax.swing.JLabel();
        jPasswordTextField = new javax.swing.JPasswordField();
        btnCreateRoles = new javax.swing.JButton();
        lblEnterprise = new javax.swing.JLabel();
        comboenterprise = new javax.swing.JComboBox<>();
        lblOrg = new javax.swing.JLabel();
        lblRoles = new javax.swing.JLabel();
        comboorgtype = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jRadioButtonInsuranceProviderRep = new javax.swing.JRadioButton();
        jRadioButtonDoctor = new javax.swing.JRadioButton();
        jRadioButtonGymTrainer = new javax.swing.JRadioButton();
        jRadioButtonPharmacist = new javax.swing.JRadioButton();
        jRadioButtonDeliveryMan = new javax.swing.JRadioButton();
        jRadioButtonDietitian = new javax.swing.JRadioButton();
        jRadioButtonCounseller = new javax.swing.JRadioButton();
        jRadioButtonLabAssistant = new javax.swing.JRadioButton();
        jComboBoxGender = new javax.swing.JComboBox<>();
        lblAddrState1 = new javax.swing.JLabel();
        lblAddrCity1 = new javax.swing.JLabel();
        txtAddressApartment = new javax.swing.JTextField();
        txtPhoneNumberAreaCode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEmailId = new javax.swing.JTextField();
        lblAddrZip1 = new javax.swing.JLabel();
        lblAddrZip2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgLogo.setBackground(new java.awt.Color(255, 255, 204));
        imgLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\sravy\\OneDrive\\Pictures\\FinalProject-Icons\\user1new.png")); // NOI18N
        imgLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(imgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 120, 120));

        btnAttach.setBackground(new java.awt.Color(255, 255, 255));
        btnAttach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/icons8-attach-30.png"))); // NOI18N
        btnAttach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttachActionPerformed(evt);
            }
        });
        jPanel1.add(btnAttach, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 40, -1));

        btnRemove1.setBackground(new java.awt.Color(255, 255, 255));
        btnRemove1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/disagree.png"))); // NOI18N
        btnRemove1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemove1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRemove1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 40, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 140, 30));

        txtName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 77, 190, 20));

        lblDob.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDob.setText("Date of Birth");
        jPanel1.add(lblDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));
        jPanel1.add(txtDobDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 190, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Phone Number");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 140, 20));

        txtPhoneNumber.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtPhoneNumber.setText("2067085330");
        txtPhoneNumber.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 186, 150, 20));

        lblAddrStreet.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblAddrStreet.setText("Community/Street");
        jPanel1.add(lblAddrStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        txtAddressStreet.setText("906 Dexter Ave N");
        txtAddressStreet.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtAddressStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 190, 20));

        lblAddrCity.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblAddrCity.setText("City");
        jPanel1.add(lblAddrCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 140, -1));

        txtAddressCity.setText("Seattle");
        txtAddressCity.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtAddressCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 190, 20));

        lblAddrZip.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblAddrZip.setText("ZIP");
        jPanel1.add(lblAddrZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 140, -1));

        txtAddressZip.setText("98109");
        txtAddressZip.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtAddressZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressZipActionPerformed(evt);
            }
        });
        jPanel1.add(txtAddressZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 387, 190, 20));

        jComboBoxAddrState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "MA", "WA", "TX", "CA", " " }));
        jComboBoxAddrState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAddrStateActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxAddrState, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 416, 190, 20));

        lblAddrState.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblAddrState.setText("State");
        jPanel1.add(lblAddrState, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 140, -1));

        lblAddrCountry.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblAddrCountry.setText("Country");
        jPanel1.add(lblAddrCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, -1, -1));

        txtAddressCountry.setText("USA");
        txtAddressCountry.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtAddressCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 190, 20));

        jUsernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jUsernameLabel.setText("Username");
        jPanel1.add(jUsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 740, 95, 20));

        txtUsername.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtUsername.setToolTipText("Enter Username");
        txtUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 740, 200, 20));

        jPasswordLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPasswordLabel.setText("Password");
        jPanel1.add(jPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 770, 95, 29));

        jPasswordTextField.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jPasswordTextField.setToolTipText("");
        jPasswordTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 770, 200, 20));

        btnCreateRoles.setBackground(new java.awt.Color(255, 255, 255));
        btnCreateRoles.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnCreateRoles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/add.png"))); // NOI18N
        btnCreateRoles.setText("Create");
        btnCreateRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateRolesActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreateRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 800, 122, -1));

        lblEnterprise.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblEnterprise.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEnterprise.setText("Enterprise");
        jPanel1.add(lblEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, -1, -1));

        comboenterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboenterpriseActionPerformed(evt);
            }
        });
        jPanel1.add(comboenterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 200, -1));

        lblOrg.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblOrg.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblOrg.setText("Organization");
        jPanel1.add(lblOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, -1, -1));

        lblRoles.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblRoles.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRoles.setText("Roles");
        jPanel1.add(lblRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, -1, -1));

        jPanel1.add(comboorgtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, 200, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Create Roles");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 28, -1, 25));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/back.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 28, -1, 37));

        jRadioButtonInsuranceProviderRep.setText("Insurance Representative");
        jPanel1.add(jRadioButtonInsuranceProviderRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 580, -1, -1));

        jRadioButtonDoctor.setText("Primary Care Provider");
        jPanel1.add(jRadioButtonDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, -1, 20));

        jRadioButtonGymTrainer.setText("Gym Instructor/Trainer");
        jPanel1.add(jRadioButtonGymTrainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 680, -1, -1));

        jRadioButtonPharmacist.setText("Pharmacist");
        jPanel1.add(jRadioButtonPharmacist, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 620, -1, -1));

        jRadioButtonDeliveryMan.setText("Delivery Representative");
        jPanel1.add(jRadioButtonDeliveryMan, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 640, -1, -1));

        jRadioButtonDietitian.setText("Dietitian");
        jPanel1.add(jRadioButtonDietitian, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 660, -1, -1));

        jRadioButtonCounseller.setText("Mental health counseller");
        jPanel1.add(jRadioButtonCounseller, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 700, -1, -1));

        jRadioButtonLabAssistant.setText("Medical tests laboratory assistant");
        jPanel1.add(jRadioButtonLabAssistant, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 600, -1, -1));

        jComboBoxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "MALE", "FEMALE", "OTHER" }));
        jComboBoxGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGenderActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 190, -1));

        lblAddrState1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblAddrState1.setText("Gender");
        jPanel1.add(lblAddrState1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 140, -1));

        lblAddrCity1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAddrCity1.setText("Unit");
        jPanel1.add(lblAddrCity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 140, 20));

        txtAddressApartment.setText("#432");
        txtAddressApartment.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtAddressApartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 190, 20));

        txtPhoneNumberAreaCode.setEditable(false);
        txtPhoneNumberAreaCode.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtPhoneNumberAreaCode.setText("+1");
        txtPhoneNumberAreaCode.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtPhoneNumberAreaCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 186, 34, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Email ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 140, 30));

        txtEmailId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtEmailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 107, 190, 20));

        lblAddrZip1.setFont(new java.awt.Font("Lucida Grande", 2, 9)); // NOI18N
        lblAddrZip1.setText("*10 digits");
        jPanel1.add(lblAddrZip1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, -1, -1));

        lblAddrZip2.setFont(new java.awt.Font("Lucida Grande", 2, 9)); // NOI18N
        lblAddrZip2.setText("*5 digits");
        jPanel1.add(lblAddrZip2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 1100, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 482, 1100, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 732, 1100, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/polygonal-bg1100X850.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 1100, 860));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttachActionPerformed
        // TODO add your handling code here:

        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            BufferedImage img = null;
            try {
                img = ImageIO.read(file);
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(NewRegistrationJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                //Logger.getLogger(NewRegistrationJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            Image scaled = img.getScaledInstance(120, 120, Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(scaled);
            imgLogo.setIcon(icon);

        }
    }//GEN-LAST:event_btnAttachActionPerformed

    private void btnRemove1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemove1ActionPerformed
        // TODO add your handling code here:
        logoImage = null;
        imgLogo.setIcon(logoImage);
    }//GEN-LAST:event_btnRemove1ActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void jComboBoxAddrStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAddrStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAddrStateActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void jPasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordTextFieldActionPerformed

    private void btnCreateRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateRolesActionPerformed
        //Person person = null ;
        // TODO add your handling code here:

        FieldsValidator fieldsValidator = new FieldsValidator();
        boolean error = fieldsValidator.validate(txtName, txtEmailId, txtUsername, jPasswordTextField, txtPhoneNumber, txtDobDateChooser,
                txtAddressStreet, txtAddressApartment, txtAddressCity, txtAddressZip, jComboBoxAddrState, txtAddressCountry, jComboBoxGender);
        error |= fieldsValidator.validate(comboorgtype);
        
        if (error) {
            JOptionPane.showMessageDialog(jPanel1, "There are error in some field(s). Please correct them.");
            return;
        }
        
        GlobalUserDirectory gd = system.globalUserDirectory;
 
        String name = txtName.getText();
        String emailId = txtEmailId.getText();
        String userName = txtUsername.getText();
        String password = new String(jPasswordTextField.getPassword());
        String phoneNumber = txtPhoneNumber.getText();
        Date dob = txtDobDateChooser.getDate();
        LocalDate dateOfBirth = dob.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        
        String addrCommunity = txtAddressStreet.getText();
        String addrCity = txtAddressCity.getText();
        String addrUnit = txtAddressApartment.getText();
        String addrZip = txtAddressZip.getText();
        String addrState = String.valueOf(jComboBoxAddrState.getSelectedItem());
        String addrCountry = txtAddressCountry.getText();
        Address address = new Address(addrCommunity, addrUnit, addrCity, addrZip, addrState, addrCountry);

        String selectedGender = String.valueOf(jComboBoxGender.getSelectedItem());
        Gender gender = Gender.valueOf(selectedGender);

        Organization selectedOrganization = getSelectedOrganizationFromComboList();
        int organizationId = selectedOrganization.getOrganizationId();

        if (gd.get(userName) != null) {
            JOptionPane.showMessageDialog(jPanel1, "Username already exists. Pick a different username.");
            return;
        }

        Icon logo = imgLogo.getIcon();
        UserAccount userAccount = new UserAccount(userName, password);
        Role role = getSelectedRole();
        if (role == null) {
            JOptionPane.showMessageDialog(jPanel1, "Must select a role");
            return;
        }
        
        switch (role) {
            case DOCTOR:
                Person doctor = new Doctor(name, dateOfBirth, gender, address, phoneNumber, logo, userAccount, organizationId, emailId);
                doctor.getPersonDetails().setEmailId(emailId);
                system.globalUserDirectory.createNewUser(doctor);
                break;
                
            case LABASSISTANT:
                Person labAssistant = new LaboratoryAssistant(name, dateOfBirth, gender, address, phoneNumber, logo, userAccount, organizationId, emailId);
                labAssistant.getPersonDetails().setEmailId(emailId);
                system.globalUserDirectory.createNewUser(labAssistant);
                 break;
             case INSURANCE_PROVIDER_REP:
                Person insuranceProvider = new InsuranceProviderRepresentative(name, dateOfBirth, gender, address, 
                        phoneNumber, logo, userAccount, organizationId, emailId);
                system.globalUserDirectory.createNewUser(insuranceProvider);
                 break;
                 
                 case DIETITIAN:
                 Person dietitian = new Dietitian(name, dateOfBirth, gender, address, phoneNumber,userAccount,logo, organizationId, emailId);
                 dietitian.getPersonDetails().setEmailId(emailId);
                system.globalUserDirectory.createNewUser(dietitian);
                break;
                
                  case TRAINER:
                 Person trainer = new FitnessTrainer(name, dateOfBirth, gender, address, phoneNumber,userAccount,logo, organizationId, emailId);
                system.globalUserDirectory.createNewUser(trainer);
                break;
                
                  case COUNSELOR:
                 Person counselor = new Counselor(name, dateOfBirth, gender, address, phoneNumber,userAccount,logo, organizationId, emailId);
                system.globalUserDirectory.createNewUser(counselor);
                break;
                
                case PHARMACIST:
                    //gender null for now and proper dob to be given
                    Person pharmacist = new Pharmacist(
                                                name, 
                                                LocalDate.now(), 
                                                gender, 
                                                address, 
                                                phoneNumber,
                                                logo,
                                                userAccount,
                                                organizationId,
                                                emailId
                                            );
                    system.globalUserDirectory.createNewUser(pharmacist);
                    break;
                    
                case DELIVERY_MAN:
                    //gender null for now and proper dob to be given
                    Person deliveryMan = new DeliveryMan(
                                                name,
                                                LocalDate.now(),
                                                gender,
                                                address,
                                                phoneNumber,
                                                logo,
                                                userAccount,
                                                organizationId,
                                                emailId
                                            );
                    system.globalUserDirectory.createNewUser(deliveryMan);
                    break;
                    
            case INVALID:
                JOptionPane.showMessageDialog(this, "Invalid Enterprise Details ");
             break;
       
       }

        JOptionPane.showMessageDialog(this,"user created successfully");
    }//GEN-LAST:event_btnCreateRolesActionPerformed

    private void comboenterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboenterpriseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboenterpriseActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        nextScreen(WorkArea, backPage, "SysAdminHomePage");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBoxGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGenderActionPerformed

    private void txtEmailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailIdActionPerformed

    private void txtAddressZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressZipActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttach;
    private javax.swing.JButton btnCreateRoles;
    private javax.swing.JButton btnRemove1;
    private javax.swing.JComboBox<String> comboenterprise;
    private javax.swing.JComboBox<String> comboorgtype;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBoxAddrState;
    private javax.swing.JComboBox<String> jComboBoxGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jPasswordLabel;
    private javax.swing.JPasswordField jPasswordTextField;
    private javax.swing.JRadioButton jRadioButtonCounseller;
    private javax.swing.JRadioButton jRadioButtonDeliveryMan;
    private javax.swing.JRadioButton jRadioButtonDietitian;
    private javax.swing.JRadioButton jRadioButtonDoctor;
    private javax.swing.JRadioButton jRadioButtonGymTrainer;
    private javax.swing.JRadioButton jRadioButtonInsuranceProviderRep;
    private javax.swing.JRadioButton jRadioButtonLabAssistant;
    private javax.swing.JRadioButton jRadioButtonPharmacist;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel jUsernameLabel;
    private javax.swing.JLabel lblAddrCity;
    private javax.swing.JLabel lblAddrCity1;
    private javax.swing.JLabel lblAddrCountry;
    private javax.swing.JLabel lblAddrState;
    private javax.swing.JLabel lblAddrState1;
    private javax.swing.JLabel lblAddrStreet;
    private javax.swing.JLabel lblAddrZip;
    private javax.swing.JLabel lblAddrZip1;
    private javax.swing.JLabel lblAddrZip2;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblOrg;
    private javax.swing.JLabel lblRoles;
    private javax.swing.JTextField txtAddressApartment;
    private javax.swing.JTextField txtAddressCity;
    private javax.swing.JTextField txtAddressCountry;
    private javax.swing.JTextField txtAddressStreet;
    private javax.swing.JTextField txtAddressZip;
    private com.toedter.calendar.JDateChooser txtDobDateChooser;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtPhoneNumberAreaCode;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

     ButtonGroup radioButtonGroup = new ButtonGroup();
    
   private void populateEnterpriseCombo() {
        comboenterprise.removeAllItems();
        comboenterprise.addItem("Select");
        for(Enterprise enterprise : system.enterpriseDirectory.getAllValidEnterprise()) {
            comboenterprise.addItem(enterprise.getEnterpriseName() + ":" + enterprise.getEnterpriseId());
        }

        comboenterprise.addItemListener(new ItemListener() {
            
            CreateRolesJPanel manageRole = null;
            
            @Override
            public void itemStateChanged(ItemEvent e) {
                disableAllRolesRadioButtons();
                Enterprise enterprise = manageRole.getSelectedEnterpriseFromComboList();
                if (enterprise == null) {
                    // do nothing
                    return;
                }
                manageRole.populateOrganizationCombo(enterprise.getOrganizations());
            }
            
             private ItemListener init(CreateRolesJPanel manageRole){
                this.manageRole = manageRole;
                return this;
            }
        }.init(this));
   }
   
   private Enterprise getSelectedEnterpriseFromComboList() {
        String selectEnterprise = (String) comboenterprise.getSelectedItem();
        if (selectEnterprise == null) {
            return null;
        }
        
        if ("Select".equals(selectEnterprise)) {
            // Do nothing
            return null;
        }

        String[] splitResult = selectEnterprise.split(":");
        String enterpriseName = splitResult[0];
        int enterpriseId = Integer.parseInt(splitResult[1]);
        Enterprise enterprise = system.enterpriseDirectory.getEnterprise(enterpriseId);
        if (enterprise == null) {
            JOptionPane.showMessageDialog(jPanel1, "No enterprise found for id " + enterpriseId + "and name " + enterpriseName);
            return null;
        }
        return enterprise;
   }
   
   private Organization getSelectedOrganizationFromComboList() {
       
        String selectedOrganization = (String) comboorgtype.getSelectedItem();
        if (selectedOrganization == null) {
            return null;
        }
        
        if ("Select".equals(selectedOrganization)) {
            // Do nothing
            return null;
        }
        
        Enterprise selectedEnterprise = getSelectedEnterpriseFromComboList();

        String[] splitResult = selectedOrganization.split(":");
        String orgName = splitResult[0];
        int orgId = Integer.parseInt(splitResult[1]);
        Organization organization = selectedEnterprise.getOrganization(orgId);
        if (organization == null) {
            JOptionPane.showMessageDialog(jPanel1, "No organization found for id " + orgId + "and name " + orgName);
            return null;
        }
        return organization;
   }

    private void populateOrganizationCombo(List<Organization> organizations) {
        comboorgtype.removeAllItems();
        comboorgtype.addItem("Select");
        
        if (organizations == null || organizations.isEmpty()) {
            return;
        }
        
        for (Organization organization : organizations) {
            comboorgtype.addItem(organization.getName() + ":" + organization.getOrganizationId());
        }
        
        comboorgtype.addItemListener(new ItemListener() {
            
            CreateRolesJPanel manageRole = null;
            
            @Override
            public void itemStateChanged(ItemEvent e) {
                disableAllRolesRadioButtons();
                Organization organization = manageRole.getSelectedOrganizationFromComboList();
                if (organization == null) {
                    // do nothing
                    return;
                }
                
                manageRole.enableRadioButton(organization.getOrganizationType());
            }
             private ItemListener init(CreateRolesJPanel manageRole){
                this.manageRole = manageRole;
                return this;
            }
        }.init(this));
        
    }
    
    private void initializeRadioButtonGroup() {
        this.radioButtonGroup.add(jRadioButtonDoctor);
        this.radioButtonGroup.add(jRadioButtonLabAssistant);
        this.radioButtonGroup.add(jRadioButtonInsuranceProviderRep);
        this.radioButtonGroup.add(jRadioButtonPharmacist);
        this.radioButtonGroup.add(jRadioButtonDeliveryMan);
        this.radioButtonGroup.add(jRadioButtonDietitian);
        this.radioButtonGroup.add(jRadioButtonGymTrainer);
        this.radioButtonGroup.add(jRadioButtonCounseller);
    }
    
    private Role getSelectedRole() {
        if (jRadioButtonDoctor.isSelected()) {
            return Role.DOCTOR;
        }
        
        if (jRadioButtonLabAssistant.isSelected()) {
            return Role.LABASSISTANT;
        }
                
        if (jRadioButtonInsuranceProviderRep.isSelected()) {
            return Role.INSURANCE_PROVIDER_REP;
                    
        }
                 
                 
        if (jRadioButtonPharmacist.isSelected()) {
            return Role.PHARMACIST;
        }
                 
                 
        if (jRadioButtonDeliveryMan.isSelected()) {
            return Role.DELIVERY_MAN;
        }
                 
                 
        if (jRadioButtonDietitian.isSelected()) {
            return Role.DIETITIAN;
        }
        
        if (jRadioButtonGymTrainer.isSelected()) {
            return Role.TRAINER;
        }
                
        if (jRadioButtonCounseller.isSelected()) {
            return Role.COUNSELOR;
        }
        
        return null;
    }
    
    private void enableRadioButton(OrganizationType organizationType) {
        log.debug("Selected organization type = " + organizationType.toString());
        switch (organizationType) {
            case PRIMARY_CARE:
                jRadioButtonDoctor.setEnabled(true);
                jRadioButtonDoctor.setSelected(true);
                break;
            case LABORATORY:
                jRadioButtonLabAssistant.setEnabled(true);
                jRadioButtonLabAssistant.setSelected(true);
                break;
            case HEALTH_INSURANCE_DEPARTMENT:
                jRadioButtonInsuranceProviderRep.setEnabled(true);
                jRadioButtonInsuranceProviderRep.setSelected(true);
                break;
            case MEDICINE_INVENTORY:
                jRadioButtonPharmacist.setEnabled(true);
                jRadioButtonPharmacist.setSelected(true);
                break;
            case DELIVERY_DEPARTMENT:
                jRadioButtonDeliveryMan.setEnabled(true);
                jRadioButtonDeliveryMan.setSelected(true);
                break;
            case NUTRITION_DEPARTMENT:
                jRadioButtonDietitian.setEnabled(true);
                jRadioButtonDietitian.setSelected(true);
                break;
            case GYM:
                jRadioButtonGymTrainer.setEnabled(true);
                jRadioButtonGymTrainer.setSelected(true);
                break;
            case PSYCHIATRY_DEPARTMENT:
                jRadioButtonCounseller.setEnabled(true);
                jRadioButtonCounseller.setSelected(true);
                break;
            default:
                break;
        }
    }
    
    private void disableAllRolesRadioButtons() {

        jRadioButtonCounseller.setSelected(false);
        jRadioButtonDeliveryMan.setSelected(false);
        jRadioButtonDietitian.setSelected(false);
        jRadioButtonDoctor.setSelected(false);
        jRadioButtonGymTrainer.setSelected(false);
        jRadioButtonInsuranceProviderRep.setSelected(false);
        jRadioButtonLabAssistant.setSelected(false);
        jRadioButtonPharmacist.setSelected(false);
        
        jRadioButtonCounseller.setEnabled(false);
        jRadioButtonDeliveryMan.setEnabled(false);
        jRadioButtonDietitian.setEnabled(false);
        jRadioButtonDoctor.setEnabled(false);
        jRadioButtonGymTrainer.setEnabled(false);
        jRadioButtonInsuranceProviderRep.setEnabled(false);
        jRadioButtonLabAssistant.setEnabled(false);
        jRadioButtonPharmacist.setEnabled(false);

    }
}
