/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SysAdminUI;

import EcoSystem.EcoSystem;
import Enterprise.Enterprise;
import Enterprise.EnterpriseType;
import Enterprise.HealthManagementAppEnterprise;
import Enterprise.HospitalEnterprise;
import Enterprise.InsuranceCompanyEnterprise;
import Enterprise.MentalWellnessEnterprise;
import Enterprise.PharmacyEnterprise;
import Enterprise.PhysicalWellnessEnterprise;
import Personnel.Address;
import Personnel.PersonDetails;
import java.awt.CardLayout;
import java.awt.Component;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author preet
 */
public class ManageEnterprises extends javax.swing.JPanel {
 JPanel WorkArea;
 EcoSystem system;
    /**
     * Creates new form CreateEnterprise
     */
    public ManageEnterprises(JPanel WorkArea,EcoSystem system) {
        initComponents();
        this.setSize(1100,850);
        this.WorkArea=WorkArea;
        this.system=system;
        jComboBox1.setModel(new DefaultComboBoxModel(EnterpriseType.values()));
        LoadEnterprises();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblenterprise = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtstreet = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtapt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtcity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtzip = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtstate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtcountry = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblenterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EnterpriseID", "Name", "Address", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblenterprise);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 880, 249));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/back.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 15, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manage an Enterprise");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Enterprise Type");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 120, 30));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 200, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Enterprise Name ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 120, 30));

        txtname.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 200, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Street");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 120, 30));

        txtstreet.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtstreet.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        add(txtstreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 200, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Apartment");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 120, 30));

        txtapt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtapt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        add(txtapt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 200, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("City");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 120, 30));

        txtcity.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtcity.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        add(txtcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 200, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("ZIP");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 610, 120, 20));

        txtzip.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtzip.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        add(txtzip, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 610, 200, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("State");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 650, 120, 20));

        txtstate.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtstate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        add(txtstate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 650, 200, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Country");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 700, 130, -1));

        txtcountry.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtcountry.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        add(txtcountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 690, 200, 20));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/add.png"))); // NOI18N
        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 740, 120, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/polygonal-bg1100X850.jpg"))); // NOI18N
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 1100, 850));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        WorkArea.remove(this);
        Component[] componentArray = WorkArea.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout)WorkArea.getLayout();
        layout.previous(WorkArea);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Address sampleAddress = new Address(txtstreet.getText(), txtapt.getText(), txtcity.getText(), txtzip.getText(), txtstate.getText(), txtcountry.getText());
        EnterpriseType type = (EnterpriseType) jComboBox1.getSelectedItem();

        switch (type) {
            case HEALTH_MANAGEMENT_APP:

            Enterprise e1 = new HealthManagementAppEnterprise(txtname.getText(), sampleAddress);
            system.enterpriseDirectory.addEnterprise(e1);
            LoadEnterprises();
            break;

            case HOSPITAL:
            Enterprise e2 = new HospitalEnterprise(txtname.getText(), sampleAddress);
            system.enterpriseDirectory.addEnterprise(e2);
            LoadEnterprises();
            break;

            case INSURANCE_COMPANY:
            Enterprise e3 = new InsuranceCompanyEnterprise(txtname.getText(), sampleAddress);
            system.enterpriseDirectory.addEnterprise(e3);
            LoadEnterprises();
            break;

            case PHARMACY:
            Enterprise pharEnterprise = new PharmacyEnterprise(txtname.getText(), sampleAddress);
            system.enterpriseDirectory.addEnterprise(pharEnterprise);
            LoadEnterprises();
            break;

            case PHYSICAL_WELLNESS:
            Enterprise e5 = new PhysicalWellnessEnterprise(txtname.getText(), sampleAddress);
            system.enterpriseDirectory.addEnterprise(e5);
            LoadEnterprises();
            break;

            case MENTAL_HEALTH:

            Enterprise e6 = new MentalWellnessEnterprise(txtname.getText(), sampleAddress);
            system.enterpriseDirectory.addEnterprise(e6);
            LoadEnterprises();
            break;
            case INVALID:
            JOptionPane.showMessageDialog(this, "Invalid Enterprise Details ");
            break;

        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<EnterpriseType> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblenterprise;
    private javax.swing.JTextField txtapt;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtcountry;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtstate;
    private javax.swing.JTextField txtstreet;
    private javax.swing.JTextField txtzip;
    // End of variables declaration//GEN-END:variables

    private void LoadEnterprises() {
         DefaultTableModel model = (DefaultTableModel) tblenterprise.getModel();
         model.setRowCount(0);
         List<Enterprise> temp;
         temp = system.enterpriseDirectory.getAllEnterprise();
      model.setRowCount(0);
        for(int i=0;i<temp.size();i++)
    {
       
                Object row[] = new Object[4];
                row[0] = temp.get(i).getEnterpriseId();
                row[1] = temp.get(i).getEnterpriseName();
                row[2]=temp.get(i).getEnterpriseType();
                row[3]=temp.get(i).getEnterpriseAddress();
                model.addRow(row);
    
    } 
     
     
     
     
    }
}
