/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SysAdminUI;

import Counselor.Counselor;
import DataStore.CredentialsManager;
import DataStore.GlobalUserDirectory;
import Dietitian.Dietitian;
import Doctor.Doctor;
import EcoSystem.EcoSystem;
import Enterprise.Enterprise;
import Enterprise.EnterpriseType;
import Enterprise.HealthManagementAppEnterprise;
import Enterprise.HospitalEnterprise;
import Enterprise.InsuranceCompanyEnterprise;
import Enterprise.MentalWellnessEnterprise;
import Enterprise.PhysicalWellnessEnterprise;
import FitnessTrainer.FitnessTrainer;
import Insurance.InsuranceProviderRepresentative;
import Laboratory.LaboratoryAssistant;
import Organization.Organization;
import Organization.OrganizationType;
import Patient.Patient;
import PatientCoreWorkFlowUI.DoctorHomePagePanel;
import Personnel.Address;
import Personnel.Person;
import Personnel.PersonDetails;
import Personnel.Role;
import Personnel.UserAccount;
import Utils.ConsoleLogger;
import Utils.NextScreen;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.time.Instant;
import java.time.LocalDate;
import java.util.Date;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author mrs.katey
 */
public class ManageRoles extends javax.swing.JPanel implements NextScreen {
   JPanel WorkArea;
   EcoSystem system;
   Person person;
   ImageIcon logoImage;
   private final JFileChooser fileChooser = new JFileChooser();
   ConsoleLogger log = ConsoleLogger.getLogger();
   
    /**
     * Creates new form ManageRoles
     */
    public ManageRoles(JPanel WorkArea, EcoSystem system) {
        initComponents();
        this.WorkArea = WorkArea;
        this.system = system;
        this.person = person;
        GlobalUserDirectory globalUserDirectory;
        FileFilter jpegFilter = new FileNameExtensionFilter("JPEG file" , "jpg" , "jpeg");
        FileFilter pngFilter = new FileNameExtensionFilter("PNG file" , "png" , "png");
        
       
        fileChooser.addChoosableFileFilter(jpegFilter);
        fileChooser.addChoosableFileFilter(pngFilter);
        fileChooser.setFileFilter(pngFilter);
        populateEnterpriseCombo();
        populateOrganizationCombo(null);
        disableAllRolesRadioButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSelectRoleLabel = new javax.swing.JLabel();
        imgLogo = new javax.swing.JLabel();
        btnAttach = new javax.swing.JButton();
        btnRemove1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblDob = new javax.swing.JLabel();
        txtDobDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        lblAddrStreet = new javax.swing.JLabel();
        txtAddressStreet = new javax.swing.JTextField();
        lblAddrCity = new javax.swing.JLabel();
        txtAddressCity = new javax.swing.JTextField();
        lblAddrZip = new javax.swing.JLabel();
        txtAddressZip = new javax.swing.JTextField();
        jComboBoxAddrState = new javax.swing.JComboBox<>();
        lblAddrState = new javax.swing.JLabel();
        lblAddrCountry = new javax.swing.JLabel();
        txtAddressCountry = new javax.swing.JTextField();
        jUsernameLabel = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jPasswordLabel = new javax.swing.JLabel();
        jPasswordTextField = new javax.swing.JPasswordField();
        btnCreateRoles = new javax.swing.JButton();
        lblEnterprise = new javax.swing.JLabel();
        comboenterprise = new javax.swing.JComboBox<>();
        lblOrg = new javax.swing.JLabel();
        lblRoles = new javax.swing.JLabel();
        comboorgtype = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jRadioButtonInsuranceProviderRep = new javax.swing.JRadioButton();
        jRadioButtonDoctor = new javax.swing.JRadioButton();
        jRadioButtonGymTrainer = new javax.swing.JRadioButton();
        jRadioButtonPharmacist = new javax.swing.JRadioButton();
        jRadioButtonDeliveryMan = new javax.swing.JRadioButton();
        jRadioButtonDietitian = new javax.swing.JRadioButton();
        jRadioButtonCounseller = new javax.swing.JRadioButton();
        jRadioButtonLabAssistant = new javax.swing.JRadioButton();

        jSelectRoleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jSelectRoleLabel.setText("Profile Picture");

        imgLogo.setBackground(new java.awt.Color(255, 255, 204));
        imgLogo.setText("Upload your photo here");

        btnAttach.setBackground(new java.awt.Color(255, 255, 102));
        btnAttach.setText("Attach");
        btnAttach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttachActionPerformed(evt);
            }
        });

        btnRemove1.setBackground(new java.awt.Color(204, 204, 255));
        btnRemove1.setText("Remove");
        btnRemove1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemove1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Name:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        lblDob.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblDob.setText("Dob:");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Phone Number:");

        lblAddress.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblAddress.setText("Address:");

        lblAddrStreet.setText("Community/Street");

        lblAddrCity.setText("City");

        lblAddrZip.setText("Zip");

        jComboBoxAddrState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "MA", "WA", "TX", "CA", " " }));
        jComboBoxAddrState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAddrStateActionPerformed(evt);
            }
        });

        lblAddrState.setText("State");

        lblAddrCountry.setText("Country");

        txtAddressCountry.setText("USA");

        jUsernameLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jUsernameLabel.setText("Username");

        txtUsername.setToolTipText("Enter Username");
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        jPasswordLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jPasswordLabel.setText("Password");

        jPasswordTextField.setToolTipText("");
        jPasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordTextFieldActionPerformed(evt);
            }
        });

        btnCreateRoles.setBackground(new java.awt.Color(0, 153, 153));
        btnCreateRoles.setText("CREATE");
        btnCreateRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateRolesActionPerformed(evt);
            }
        });

        lblEnterprise.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEnterprise.setText("Enterprise:");

        comboenterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboenterpriseActionPerformed(evt);
            }
        });

        lblOrg.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblOrg.setText("Organization");

        lblRoles.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRoles.setText("Roles");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Create Roles");

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jRadioButtonInsuranceProviderRep.setText("Insurance Representative");

        jRadioButtonDoctor.setText("Primary Care Provider");

        jRadioButtonGymTrainer.setText("Gym Instructor/Trainer");

        jRadioButtonPharmacist.setText("Pharmacy Manager");

        jRadioButtonDeliveryMan.setText("Shipping/Delivery Representative");

        jRadioButtonDietitian.setText("Dietitian");

        jRadioButtonCounseller.setText("Mental health counseller");

        jRadioButtonLabAssistant.setText("Medical tests laboratory assistant");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDob)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtName)
                    .addComponent(txtDobDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addGap(467, 467, 467))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblAddrStreet)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblAddrZip)
                                                .addComponent(lblAddrCity)))
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAddressStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAddressCity, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtAddressZip, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(43, 43, 43)
                                                .addComponent(lblAddrState)
                                                .addGap(32, 32, 32)
                                                .addComponent(jComboBoxAddrState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addComponent(lblAddrCountry)
                                        .addGap(12, 12, 12)
                                        .addComponent(txtAddressCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jSelectRoleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jButton4)))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(140, 140, 140)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(btnRemove1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                    .addComponent(btnAttach, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(jLabel6))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblOrg)
                                    .addComponent(lblEnterprise)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(lblRoles)))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(comboenterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboorgtype, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonLabAssistant)
                                    .addComponent(jRadioButtonDoctor)
                                    .addComponent(jRadioButtonPharmacist)
                                    .addComponent(jRadioButtonGymTrainer)
                                    .addComponent(jRadioButtonDeliveryMan)
                                    .addComponent(jRadioButtonDietitian)
                                    .addComponent(jRadioButtonCounseller)
                                    .addComponent(jRadioButtonInsuranceProviderRep)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(btnCreateRoles, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jSelectRoleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btnAttach)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRemove1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel1))
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblDob))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtDobDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(lblAddrStreet)
                    .addComponent(txtAddressStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddressCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddrCity))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddrZip)
                    .addComponent(txtAddressZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddrState)
                    .addComponent(jComboBoxAddrState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddrCountry)
                    .addComponent(txtAddressCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterprise)
                    .addComponent(comboenterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrg)
                    .addComponent(comboorgtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblRoles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonInsuranceProviderRep)
                        .addGap(3, 3, 3)
                        .addComponent(jRadioButtonLabAssistant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonPharmacist)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonDeliveryMan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonDietitian)
                        .addGap(12, 12, 12)
                        .addComponent(jRadioButtonGymTrainer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonCounseller)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCreateRoles)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttachActionPerformed
        // TODO add your handling code here:

        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            BufferedImage img = null;
            try {
                img = ImageIO.read(file);
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(NewRegistrationJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                //Logger.getLogger(NewRegistrationJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            Image scaled = img.getScaledInstance(120, 120, Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(scaled);
            imgLogo.setIcon(icon);

        }
    }//GEN-LAST:event_btnAttachActionPerformed

    private void btnRemove1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemove1ActionPerformed
        // TODO add your handling code here:
        logoImage = null;
        imgLogo.setIcon(logoImage);
    }//GEN-LAST:event_btnRemove1ActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void jComboBoxAddrStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAddrStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAddrStateActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void jPasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordTextFieldActionPerformed

    private void btnCreateRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateRolesActionPerformed
        //Person person = null ;
        // TODO add your handling code here:

        GlobalUserDirectory gd = system.globalUserDirectory;
        String name = txtName.getText();
        if (name == null || name.isEmpty()) {
            JOptionPane.showMessageDialog(jPanel1, "name cannot be empty");
            return;
        }

        String userName = txtUsername.getText();
        if (userName == null || userName.isEmpty()) {
            JOptionPane.showMessageDialog(jPanel1, "username cannot be empty");
            return;
        }

        String password = new String(jPasswordTextField.getPassword());
        if (password == null || password.isEmpty()) {
            JOptionPane.showMessageDialog(jPanel1, "password cannot be empty");
            return;
        }

        String phoneNumber = txtPhoneNumber.getText();
        if (phoneNumber == null || phoneNumber.isEmpty()) {
            JOptionPane.showMessageDialog(jPanel1, "phone number cannot be empty");
            return;
        }
        Date dob = txtDobDateChooser.getDate();
        Date currentDate = Date.from(Instant.now());
        if (dob.after(currentDate)) {
            JOptionPane.showMessageDialog(jPanel1, "Date of Birth must be older than current date");
            return;
        }

        try {
            Long.parseLong(phoneNumber);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(jPanel1, "Invalid phone number. Expected numbers only.");
            return;
        }

        if (phoneNumber.length() != 10) {
            JOptionPane.showMessageDialog(jPanel1, "Invalid phone number. Expected 10 digit number.");
            return;
        }

        String addrCommunity = txtAddressStreet.getText();
        String addrCity = txtAddressCity.getText();
        String addrZip = txtAddressZip.getText();
        String addrState = String.valueOf(jComboBoxAddrState.getSelectedItem());
        if (addrState.equals("Select")) {
                JOptionPane.showMessageDialog(jPanel1, "Select a valid state.");
                 return;
            }
        String addrCountry = txtAddressCountry.getText();
        // String street, String apartment, String city, String zipcode, String state, String country
        Address address = new Address(null, null, addrCity, addrZip, addrState, addrCountry);
        
        if (gd.get(userName) != null) {
            JOptionPane.showMessageDialog(jPanel1, "Username already exists. Pick a different username.");
            return;
        }

        System.out.println("Date: " + dob.toString());
         Address sampleAddress = new Address(txtAddressStreet.getText(),null, txtAddressCity.getText(), txtAddressZip.getText(), null, txtAddressCountry.getText());
         //Address house = new Address(addrCommunity, addrZip,  addrCity,  addrState,  addrCountry);

        Icon logo = imgLogo.getIcon();
          
        UserAccount userAccount = new UserAccount(userName, password);
        Organization selectedOrganization = getSelectedOrganizationFromComboList();
        if (selectedOrganization == null) {
            JOptionPane.showMessageDialog(jPanel1, "Select a valid organization from the list");
            return;
        }
        
        int organizationId = selectedOrganization.getOrganizationId();
        Role role = getSelectedRole();
        if (role == null) {
            JOptionPane.showMessageDialog(jPanel1, "Select a valid role");
            return;
        }
        
        
        
        switch (role) {
            case DOCTOR:
                Person doctor = new Doctor(name, null, null, address, phoneNumber, logo, userAccount, organizationId);
                system.globalUserDirectory.createNewUser(doctor);
                break;
                
            case LABASSISTANT:
                Person labAssistant = new LaboratoryAssistant(name, null, null, address, phoneNumber, logo, userAccount, organizationId);
                system.globalUserDirectory.createNewUser(labAssistant);
                 break;
             case INSURANCE_PROVIDER_REP:
                Person insuranceProvider = new InsuranceProviderRepresentative(name, null, null, address, phoneNumber, logo, userAccount, organizationId);
                system.globalUserDirectory.createNewUser(insuranceProvider);
                 break;
                 
                 case DIETITIAN:
                 Person dietitian = new Dietitian(name, null, null, address, phoneNumber,userAccount,logo, organizationId);
                system.globalUserDirectory.createNewUser(dietitian);
                break;
                
                  case TRAINER:
                 Person trainer = new FitnessTrainer(name, null, null, address, phoneNumber,userAccount,logo, organizationId);
                system.globalUserDirectory.createNewUser(trainer);
                break;
                
                  case COUNSELOR:
                 Person counselor = new Counselor(name, null, null, address, phoneNumber,userAccount,logo, organizationId);
                system.globalUserDirectory.createNewUser(counselor);
                break;
                

            case INVALID:
                JOptionPane.showMessageDialog(this, "Invalid Enterprise Details ");
             break;
       
       }
      


        JOptionPane.showMessageDialog(this,"user created");
    }//GEN-LAST:event_btnCreateRolesActionPerformed

    private void comboenterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboenterpriseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboenterpriseActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        WorkArea.remove(this);
        Component[] componentArray = WorkArea.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout)WorkArea.getLayout();
        layout.previous(WorkArea);
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttach;
    private javax.swing.JButton btnCreateRoles;
    private javax.swing.JButton btnRemove1;
    private javax.swing.JComboBox<String> comboenterprise;
    private javax.swing.JComboBox<String> comboorgtype;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBoxAddrState;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jPasswordLabel;
    private javax.swing.JPasswordField jPasswordTextField;
    private javax.swing.JRadioButton jRadioButtonCounseller;
    private javax.swing.JRadioButton jRadioButtonDeliveryMan;
    private javax.swing.JRadioButton jRadioButtonDietitian;
    private javax.swing.JRadioButton jRadioButtonDoctor;
    private javax.swing.JRadioButton jRadioButtonGymTrainer;
    private javax.swing.JRadioButton jRadioButtonInsuranceProviderRep;
    private javax.swing.JRadioButton jRadioButtonLabAssistant;
    private javax.swing.JRadioButton jRadioButtonPharmacist;
    private javax.swing.JLabel jSelectRoleLabel;
    private javax.swing.JLabel jUsernameLabel;
    private javax.swing.JLabel lblAddrCity;
    private javax.swing.JLabel lblAddrCountry;
    private javax.swing.JLabel lblAddrState;
    private javax.swing.JLabel lblAddrStreet;
    private javax.swing.JLabel lblAddrZip;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblOrg;
    private javax.swing.JLabel lblRoles;
    private javax.swing.JTextField txtAddressCity;
    private javax.swing.JTextField txtAddressCountry;
    private javax.swing.JTextField txtAddressStreet;
    private javax.swing.JTextField txtAddressZip;
    private com.toedter.calendar.JDateChooser txtDobDateChooser;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

     ButtonGroup radioButtonGroup = new ButtonGroup();
    
   private void populateEnterpriseCombo() {
        comboenterprise.removeAllItems();
        comboenterprise.addItem("Select Enterprise");
        for(Enterprise enterprise : system.enterpriseDirectory.getAllEnterprise()) {
            comboenterprise.addItem(enterprise.getEnterpriseName() + ":" + enterprise.getEnterpriseId());
        }

        comboenterprise.addItemListener(new ItemListener() {
            
            ManageRoles manageRole = null;
            
            @Override
            public void itemStateChanged(ItemEvent e) {
                disableAllRolesRadioButtons();
                Enterprise enterprise = manageRole.getSelectedEnterpriseFromComboList();
                if (enterprise == null) {
                    // do nothing
                    return;
                }
                manageRole.populateOrganizationCombo(enterprise.getOrganizations());
            }
            
             private ItemListener init(ManageRoles manageRole){
                this.manageRole = manageRole;
                return this;
            }
        }.init(this));
   }
   
   private Enterprise getSelectedEnterpriseFromComboList() {
        String selectEnterprise = (String) comboenterprise.getSelectedItem();
        if (selectEnterprise == null) {
            return null;
        }
        
        if ("Select Enterprise".equals(selectEnterprise)) {
            // Do nothing
            return null;
        }

        String[] splitResult = selectEnterprise.split(":");
        String enterpriseName = splitResult[0];
        int enterpriseId = Integer.parseInt(splitResult[1]);
        Enterprise enterprise = system.enterpriseDirectory.getEnterprise(enterpriseId);
        if (enterprise == null) {
            JOptionPane.showMessageDialog(jPanel1, "No enterprise found for id " + enterpriseId + "and name " + enterpriseName);
            return null;
        }
        return enterprise;
   }
   
   private Organization getSelectedOrganizationFromComboList() {
       
        String selectedOrganization = (String) comboorgtype.getSelectedItem();
        if (selectedOrganization == null) {
            return null;
        }
        
        if ("Select Organization".equals(selectedOrganization)) {
            // Do nothing
            return null;
        }
        
        Enterprise selectedEnterprise = getSelectedEnterpriseFromComboList();

        String[] splitResult = selectedOrganization.split(":");
        String orgName = splitResult[0];
        int orgId = Integer.parseInt(splitResult[1]);
        Organization organization = selectedEnterprise.getOrganization(orgId);
        if (organization == null) {
            JOptionPane.showMessageDialog(jPanel1, "No organization found for id " + orgId + "and name " + orgName);
            return null;
        }
        return organization;
   }

    private void populateOrganizationCombo(List<Organization> organizations) {
        comboorgtype.removeAllItems();
        comboorgtype.addItem("Select Organization");
        
        if (organizations == null || organizations.isEmpty()) {
            return;
        }
        
        for (Organization organization : organizations) {
            comboorgtype.addItem(organization.getName() + ":" + organization.getOrganizationId());
        }
        
        comboorgtype.addItemListener(new ItemListener() {
            
            ManageRoles manageRole = null;
            
            @Override
            public void itemStateChanged(ItemEvent e) {
                disableAllRolesRadioButtons();
                Organization organization = manageRole.getSelectedOrganizationFromComboList();
                if (organization == null) {
                    // do nothing
                    return;
                }
                
                manageRole.enableRadioButton(organization.getOrganizationType());
            }
             private ItemListener init(ManageRoles manageRole){
                this.manageRole = manageRole;
                return this;
            }
        }.init(this));
        
    }
    
    private void initializeRadioButtonGroup() {
        this.radioButtonGroup.add(jRadioButtonDoctor);
        this.radioButtonGroup.add(jRadioButtonLabAssistant);
        this.radioButtonGroup.add(jRadioButtonInsuranceProviderRep);
        this.radioButtonGroup.add(jRadioButtonPharmacist);
        this.radioButtonGroup.add(jRadioButtonDeliveryMan);
        this.radioButtonGroup.add(jRadioButtonDietitian);
        this.radioButtonGroup.add(jRadioButtonGymTrainer);
        this.radioButtonGroup.add(jRadioButtonCounseller);
    }
    
    private Role getSelectedRole() {
        if (jRadioButtonDoctor.isSelected()) {
            return Role.DOCTOR;
        }
        
        if (jRadioButtonLabAssistant.isSelected()) {
            return Role.LABASSISTANT;
        }
                
        if (jRadioButtonInsuranceProviderRep.isSelected()) {
            return Role.INSURANCE_PROVIDER_REP;
                    
        }
                 
                 
        if (jRadioButtonPharmacist.isSelected()) {
            return Role.DOCTOR;
        }
                 
                 
        if (jRadioButtonDeliveryMan.isSelected()) {
            return Role.DOCTOR;
        }
                 
                 
        if (jRadioButtonDietitian.isSelected()) {
            return Role.DOCTOR;
        }
        
        if (jRadioButtonGymTrainer.isSelected()) {
            return Role.DOCTOR;
        }
                
        if (jRadioButtonCounseller.isSelected()) {
            return Role.DOCTOR;
        }
        
        return null;
    }
    
    private void enableRadioButton(OrganizationType organizationType) {
        log.debug("Selected organization type = " + organizationType.toString());
        switch (organizationType) {
            case PRIMARY_CARE:
                jRadioButtonDoctor.setEnabled(true);
                jRadioButtonDoctor.setSelected(true);
                break;
            case LABORATORY:
                jRadioButtonLabAssistant.setEnabled(true);
                jRadioButtonLabAssistant.setSelected(true);
                break;
            case HEALTH_INSURANCE_DEPARTMENT:
                jRadioButtonInsuranceProviderRep.setEnabled(true);
                jRadioButtonInsuranceProviderRep.setSelected(true);
                break;
            case MEDICINE_INVENTORY:
                jRadioButtonPharmacist.setEnabled(true);
                jRadioButtonPharmacist.setSelected(true);
                break;
            case LOGISTICS:
                jRadioButtonDeliveryMan.setEnabled(true);
                jRadioButtonDeliveryMan.setSelected(true);
                break;
            case NUTRITION_DEPARTMENT:
                jRadioButtonDietitian.setEnabled(true);
                jRadioButtonDietitian.setSelected(true);
                break;
            case GYM:
                jRadioButtonGymTrainer.setEnabled(true);
                jRadioButtonGymTrainer.setSelected(true);
                break;
            case PSYCHIATRY_DEPARTMENT:
                jRadioButtonCounseller.setEnabled(true);
                jRadioButtonCounseller.setSelected(true);
                break;
            default:
                break;
        }
    }
    
    private void disableAllRolesRadioButtons() {

        jRadioButtonCounseller.setSelected(false);
        jRadioButtonDeliveryMan.setSelected(false);
        jRadioButtonDietitian.setSelected(false);
        jRadioButtonDoctor.setSelected(false);
        jRadioButtonGymTrainer.setSelected(false);
        jRadioButtonInsuranceProviderRep.setSelected(false);
        jRadioButtonLabAssistant.setSelected(false);
        jRadioButtonPharmacist.setSelected(false);
        
        jRadioButtonCounseller.setEnabled(false);
        jRadioButtonDeliveryMan.setEnabled(false);
        jRadioButtonDietitian.setEnabled(false);
        jRadioButtonDoctor.setEnabled(false);
        jRadioButtonGymTrainer.setEnabled(false);
        jRadioButtonInsuranceProviderRep.setEnabled(false);
        jRadioButtonLabAssistant.setEnabled(false);
        jRadioButtonPharmacist.setEnabled(false);

    }
}
