/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SysAdminUI;

import DataStore.GlobalUserDirectory;
import Doctor.Doctor;
import EcoSystem.EcoSystem;
import Enterprise.Enterprise;
import Enterprise.EnterpriseType;
import Enterprise.PharmacyEnterprise;
import Organization.Organization;
import Patient.Patient;
import Personnel.Address;
import Personnel.Person;
import Personnel.PersonDetails;
import Personnel.UserAccount;
import Utils.ConsoleLogger;
import Utils.FieldsValidator;
import Utils.NextScreen;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
//import com.github.sarxos.webcam.Webcam;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.commons.lang.StringUtils;
import org.apache.commons.validator.routines.EmailValidator;

/**
 *
 * @author Ankur Bywar
 */
public class NewRegistrationJPanel extends javax.swing.JPanel implements NextScreen {
    EcoSystem ecoSystem;
    JPanel WorkArea;
    GlobalUserDirectory globalUserDirectory;
    private final JFileChooser fileChooser = new JFileChooser();
    ImageIcon logoImage;
    ConsoleLogger log = ConsoleLogger.getLogger();
    /**
     * Creates new form NewRegistrationJPanel
     */
    public NewRegistrationJPanel(JPanel WorkArea, EcoSystem ecoSystem) {
        initComponents();
        this.ecoSystem = ecoSystem;
        this.globalUserDirectory = globalUserDirectory;
        this.WorkArea = WorkArea;
        //boolean Visible;
        
        FileFilter jpegFilter = new FileNameExtensionFilter("JPEG file" , "jpg" , "jpeg");
        FileFilter pngFilter = new FileNameExtensionFilter("PNG file" , "png" , "png");
        
        txtDobDateChooser.setMaxSelectableDate(Date.from(Instant.now().minusMillis(86400000)));
        fileChooser.addChoosableFileFilter(jpegFilter);
        fileChooser.addChoosableFileFilter(pngFilter);
        fileChooser.setFileFilter(pngFilter);
        populatePreferredPharmacy();
    }
    
    void populatePreferredPharmacy() {
        jComboBoxPreferredPharmacy.removeAllItems();
        List<Enterprise> pharmacies = ecoSystem.enterpriseDirectory.getEnterpriseByType(EnterpriseType.PHARMACY);
        if (pharmacies == null || pharmacies.isEmpty()) {
            log.error("NO PHARMACIES EXISTS FOR PATIENTS TO SELECT PREFERRED PHARMACY");
            return;
        }
        
        jComboBoxPreferredPharmacy.addItem("Select");
        for (Enterprise pharmacy : pharmacies) {
            jComboBoxPreferredPharmacy.addItem(pharmacy.getEnterpriseName() + ":" + pharmacy.getEnterpriseId());
        } 
        
        jComboBoxPreferredPharmacy.addItemListener(new ItemListener() {
            NewRegistrationJPanel parent;
            @Override
            public void itemStateChanged(ItemEvent e) {
                parent.populatePharmacyAddressPlaceHolder();
            }
            
            private ItemListener init(NewRegistrationJPanel parent) {
                this.parent = parent;
                return this;
            }  
        }.init(this));
    }
    
    void populatePharmacyAddressPlaceHolder() {
        String selectedPharmacy = (String) jComboBoxPreferredPharmacy.getSelectedItem();
        if (selectedPharmacy == null) {
            return;
        }
        
        if ("Select".equals(selectedPharmacy)) {
            lblPharmacyAddressPlaceHolder.setText("");
            return;
        }
        
        Enterprise pharmacy = ecoSystem.enterpriseDirectory.getEnterprise(Integer.parseInt(selectedPharmacy.split(":")[1]));
        if (pharmacy == null) {
            JOptionPane.showMessageDialog(jRegistrationpanel, "No pharmacy exists for the selected entry: " + selectedPharmacy);
            return;
        }
        
        lblPharmacyAddressPlaceHolder.setText("Pharmacy Address: " + pharmacy.getEnterpriseAddress().toString());
        lblPharmacyAddressPlaceHolder.setForeground(Color.GREEN);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRegistrationpanel = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        jPasswordTextField = new javax.swing.JPasswordField();
        lblDob = new javax.swing.JLabel();
        jSelectRoleLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jPasswordLabel = new javax.swing.JLabel();
        imgLogo = new javax.swing.JLabel();
        lblTitleRegister = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        btnAttach = new javax.swing.JButton();
        txtDobDateChooser = new com.toedter.calendar.JDateChooser();
        jUsernameLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        btnLoginRedirect = new javax.swing.JButton();
        btnRemove1 = new javax.swing.JButton();
        lblAddress = new javax.swing.JLabel();
        lblAddrStreet = new javax.swing.JLabel();
        lblAddrState1 = new javax.swing.JLabel();
        jComboBoxGender = new javax.swing.JComboBox<>();
        txtAddressStreet = new javax.swing.JTextField();
        lblAddrCity1 = new javax.swing.JLabel();
        txtAddressApartment = new javax.swing.JTextField();
        lblAddrCity = new javax.swing.JLabel();
        txtAddressCity = new javax.swing.JTextField();
        lblAddrZip = new javax.swing.JLabel();
        txtAddressZip = new javax.swing.JTextField();
        lblAddrState = new javax.swing.JLabel();
        jComboBoxAddrState = new javax.swing.JComboBox<>();
        lblAddrCountry = new javax.swing.JLabel();
        txtAddressCountry = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEmailId = new javax.swing.JTextField();
        txtPhoneNumberAreaCode = new javax.swing.JTextField();
        jUsernameLabel1 = new javax.swing.JLabel();
        jComboBoxPreferredPharmacy = new javax.swing.JComboBox<>();
        lblPharmacyAddressPlaceHolder = new javax.swing.JLabel();
        lblAddrZip1 = new javax.swing.JLabel();
        lblAddrZip2 = new javax.swing.JLabel();

        jPasswordTextField.setToolTipText("");
        jPasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordTextFieldActionPerformed(evt);
            }
        });

        lblDob.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblDob.setText("Dob:");

        jSelectRoleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jSelectRoleLabel.setText("Profile Picture");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Phone Number:");

        txtUsername.setToolTipText("Enter Username");
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        jPasswordLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jPasswordLabel.setText("Password");

        imgLogo.setBackground(new java.awt.Color(255, 255, 204));
        imgLogo.setText("Upload your photo here");

        lblTitleRegister.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTitleRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleRegister.setText("New User Registeration");

        btnAttach.setBackground(new java.awt.Color(255, 255, 102));
        btnAttach.setText("Attach");
        btnAttach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttachActionPerformed(evt);
            }
        });

        jUsernameLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jUsernameLabel.setText("Preferred Pharmacy");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Name:");

        btnRegister.setBackground(new java.awt.Color(0, 153, 153));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnLoginRedirect.setText("Login");
        btnLoginRedirect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginRedirectActionPerformed(evt);
            }
        });

        btnRemove1.setBackground(new java.awt.Color(204, 204, 255));
        btnRemove1.setText("Remove");
        btnRemove1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemove1ActionPerformed(evt);
            }
        });

        lblAddress.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblAddress.setText("Address:");

        lblAddrStreet.setText("Community/Street");

        lblAddrState1.setText("Gender");

        jComboBoxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "MALE", "FEMALE", "OTHER" }));
        jComboBoxGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGenderActionPerformed(evt);
            }
        });

        txtAddressStreet.setText("1232 Harrison St");

        lblAddrCity1.setText("Unit");

        txtAddressApartment.setText("#225");

        lblAddrCity.setText("City");

        txtAddressCity.setText("Seattle");

        lblAddrZip.setText("Zip");

        txtAddressZip.setText("97981");

        lblAddrState.setText("State");

        jComboBoxAddrState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "MA", "WA", "TX", "CA", " " }));
        jComboBoxAddrState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAddrStateActionPerformed(evt);
            }
        });

        lblAddrCountry.setText("Country");

        txtAddressCountry.setText("USA");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Email Id:");

        txtEmailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailIdActionPerformed(evt);
            }
        });

        txtPhoneNumberAreaCode.setEditable(false);
        txtPhoneNumberAreaCode.setText("+1");

        jUsernameLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jUsernameLabel1.setText("Username");

        jComboBoxPreferredPharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPreferredPharmacyActionPerformed(evt);
            }
        });

        lblAddrZip1.setFont(new java.awt.Font("Lucida Grande", 2, 9)); // NOI18N
        lblAddrZip1.setText("*10 digits");

        lblAddrZip2.setFont(new java.awt.Font("Lucida Grande", 2, 9)); // NOI18N
        lblAddrZip2.setText("*5 digits");

        javax.swing.GroupLayout jRegistrationpanelLayout = new javax.swing.GroupLayout(jRegistrationpanel);
        jRegistrationpanel.setLayout(jRegistrationpanelLayout);
        jRegistrationpanelLayout.setHorizontalGroup(
            jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRegistrationpanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jRegistrationpanelLayout.createSequentialGroup()
                        .addComponent(jSelectRoleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(201, 201, 201)
                        .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                        .addGroup(jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRemove1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAttach, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(213, 213, 213))
                    .addGroup(jRegistrationpanelLayout.createSequentialGroup()
                        .addGroup(jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jRegistrationpanelLayout.createSequentialGroup()
                                .addGroup(jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jRegistrationpanelLayout.createSequentialGroup()
                                        .addGap(164, 164, 164)
                                        .addGroup(jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)))
                                    .addGroup(jRegistrationpanelLayout.createSequentialGroup()
                                        .addGap(179, 179, 179)
                                        .addComponent(lblDob)))
                                .addGap(32, 32, 32)
                                .addGroup(jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtName)
                                        .addComponent(txtEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jRegistrationpanelLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDobDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jRegistrationpanelLayout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addGroup(jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAddrState1)
                                    .addGroup(jRegistrationpanelLayout.createSequentialGroup()
                                        .addGroup(jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblAddrStreet)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jRegistrationpanelLayout.createSequentialGroup()
                                                    .addGroup(jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lblAddrCity)
                                                        .addComponent(lblAddrCity1)
                                                        .addComponent(lblAddrZip))
                                                    .addGap(48, 48, 48)))
                                            .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(13, 13, 13)
                                        .addGroup(jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAddressApartment, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAddressStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAddressCity, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAddressCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jRegistrationpanelLayout.createSequentialGroup()
                                                .addComponent(txtAddressZip, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblAddrZip2)
                                                .addGap(39, 39, 39)
                                                .addComponent(lblAddrState)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBoxAddrState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jRegistrationpanelLayout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addGroup(jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTitleRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jRegistrationpanelLayout.createSequentialGroup()
                                        .addGroup(jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblAddrCountry)
                                            .addComponent(jLabel3))
                                        .addGap(24, 24, 24)
                                        .addComponent(txtPhoneNumberAreaCode, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblAddrZip1))))
                            .addGroup(jRegistrationpanelLayout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addGroup(jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jRegistrationpanelLayout.createSequentialGroup()
                                        .addComponent(jPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jRegistrationpanelLayout.createSequentialGroup()
                                        .addComponent(jUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxPreferredPharmacy, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jRegistrationpanelLayout.createSequentialGroup()
                                        .addComponent(jUsernameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(273, Short.MAX_VALUE))))
            .addGroup(jRegistrationpanelLayout.createSequentialGroup()
                .addGroup(jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jRegistrationpanelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLoginRedirect, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jRegistrationpanelLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(lblPharmacyAddressPlaceHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jRegistrationpanelLayout.setVerticalGroup(
            jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRegistrationpanelLayout.createSequentialGroup()
                .addGroup(jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jRegistrationpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitleRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSelectRoleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jRegistrationpanelLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnAttach)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemove1)))
                .addGap(88, 88, 88)
                .addGroup(jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(3, 3, 3)
                .addGroup(jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(16, 16, 16)
                .addGroup(jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDob)
                    .addComponent(txtDobDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddrState1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddrStreet)
                    .addComponent(txtAddressStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddrCity1)
                    .addComponent(txtAddressApartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddrCity)
                    .addComponent(txtAddressCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddrZip)
                    .addComponent(txtAddressZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddrState)
                    .addComponent(jComboBoxAddrState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddrZip2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddrCountry)
                    .addComponent(txtAddressCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneNumberAreaCode, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddrZip1))
                .addGap(40, 40, 40)
                .addGroup(jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPreferredPharmacy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPharmacyAddressPlaceHolder)
                .addGap(13, 13, 13)
                .addGroup(jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUsernameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jRegistrationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(btnRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLoginRedirect, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRegistrationpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRegistrationpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordTextFieldActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnAttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttachActionPerformed
        // TODO add your handling code here:

         int returnVal = fileChooser.showOpenDialog(this);
         if (returnVal == JFileChooser.APPROVE_OPTION) {
             File file = fileChooser.getSelectedFile();
             BufferedImage img = null;
             try {
                 img = ImageIO.read(file);
             } catch (IOException ex) {
                 java.util.logging.Logger.getLogger(NewRegistrationJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
               //Logger.getLogger(NewRegistrationJPanel.class.getName()).log(Level.SEVERE, null, ex);  
             }
             Image scaled = img.getScaledInstance(120, 120, Image.SCALE_SMOOTH);
             ImageIcon icon = new ImageIcon(scaled);
             imgLogo.setIcon(icon);
             
         }
    }//GEN-LAST:event_btnAttachActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        //Person person = null ;
        // TODO add your handling code here:
        
        FieldsValidator fieldsValidator = new FieldsValidator();
        boolean error = fieldsValidator.validate(txtName, txtEmailId, txtUsername, jPasswordTextField, txtPhoneNumber, txtDobDateChooser,
                txtAddressStreet, txtAddressApartment, txtAddressCity, txtAddressZip, jComboBoxAddrState, txtAddressCountry, jComboBoxGender);
        error |= fieldsValidator.validate(jComboBoxPreferredPharmacy);
        if (error) {
            JOptionPane.showMessageDialog(jRegistrationpanel, "There are error in some field(s). Please correct them.");
            return;
        }
        
        GlobalUserDirectory gd = ecoSystem.globalUserDirectory;
 
        String name = txtName.getText();
        String emailId = txtEmailId.getText();
        String userName = txtUsername.getText();
        String password = new String(jPasswordTextField.getPassword());
        String phoneNumber = txtPhoneNumber.getText();
        Date dob = txtDobDateChooser.getDate();
        LocalDate dateOfBirth = dob.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        
        String addrCommunity = txtAddressStreet.getText();
        String addrCity = txtAddressCity.getText();
        String addrUnit = txtAddressApartment.getText();
        String addrZip = txtAddressZip.getText();
        String addrState = String.valueOf(jComboBoxAddrState.getSelectedItem());
        String addrCountry = txtAddressCountry.getText();
        Address address = new Address(addrCommunity, addrUnit, addrCity, addrZip, addrState, addrCountry);

        String selectedGender = String.valueOf(jComboBoxGender.getSelectedItem());
        PersonDetails.Gender gender = PersonDetails.Gender.valueOf(selectedGender);


        if (gd.get(userName) != null) {
            JOptionPane.showMessageDialog(jRegistrationpanel, "Username already exists. Pick a different username.");
            return;
        }

        Icon logo = imgLogo.getIcon();
        UserAccount userAccount = new UserAccount(userName, password);
        
        String selectedPreferredPharmacy = (String)jComboBoxPreferredPharmacy.getSelectedItem();
        Enterprise preferredPharmacy = ecoSystem.enterpriseDirectory.getEnterprise(Integer.parseInt(selectedPreferredPharmacy.split(":")[1]));
        if (preferredPharmacy == null) {
            JOptionPane.showMessageDialog(jRegistrationpanel, "No pharmacy found for selected item: " + selectedPreferredPharmacy);
            return;
        }
        
        Person patient = new Patient(name, dateOfBirth, gender, address, phoneNumber, logo, userAccount, -1, (PharmacyEnterprise)preferredPharmacy, emailId);
                ecoSystem.globalUserDirectory.createNewUser(patient);
        
         gd.createNewUser(patient);
        
       // gd.createNewUser(person);
        JOptionPane.showMessageDialog(this,"registered info saved");
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnLoginRedirectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginRedirectActionPerformed
        // TODO add your handling code here:
        //nextScreen(new Login(dataStore, mainWorkArea, mainJFrame), "Login");
        nextScreen(new Login(WorkArea, ecoSystem), "Login");
    }//GEN-LAST:event_btnLoginRedirectActionPerformed

    private void btnRemove1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemove1ActionPerformed
        // TODO add your handling code here:
        logoImage = null;
        imgLogo.setIcon(logoImage);
    }//GEN-LAST:event_btnRemove1ActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void jComboBoxAddrStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAddrStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAddrStateActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
//        WorkArea.remove(this);
//        Component[] componentArray = WorkArea.getComponents();
//        Component component = componentArray[componentArray.length - 1];
//        CardLayout layout = (CardLayout)WorkArea.getLayout();
//        layout.previous(WorkArea);
         nextScreen(WorkArea, new Login(WorkArea, ecoSystem), "Login   ");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBoxGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGenderActionPerformed

    private void txtEmailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailIdActionPerformed

    private void jComboBoxPreferredPharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPreferredPharmacyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPreferredPharmacyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttach;
    private javax.swing.JButton btnLoginRedirect;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnRemove1;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JComboBox<String> jComboBoxAddrState;
    private javax.swing.JComboBox<String> jComboBoxGender;
    private javax.swing.JComboBox<String> jComboBoxPreferredPharmacy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jPasswordLabel;
    private javax.swing.JPasswordField jPasswordTextField;
    private javax.swing.JPanel jRegistrationpanel;
    private javax.swing.JLabel jSelectRoleLabel;
    private javax.swing.JLabel jUsernameLabel;
    private javax.swing.JLabel jUsernameLabel1;
    private javax.swing.JLabel lblAddrCity;
    private javax.swing.JLabel lblAddrCity1;
    private javax.swing.JLabel lblAddrCountry;
    private javax.swing.JLabel lblAddrState;
    private javax.swing.JLabel lblAddrState1;
    private javax.swing.JLabel lblAddrStreet;
    private javax.swing.JLabel lblAddrZip;
    private javax.swing.JLabel lblAddrZip1;
    private javax.swing.JLabel lblAddrZip2;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblPharmacyAddressPlaceHolder;
    private javax.swing.JLabel lblTitleRegister;
    private javax.swing.JTextField txtAddressApartment;
    private javax.swing.JTextField txtAddressCity;
    private javax.swing.JTextField txtAddressCountry;
    private javax.swing.JTextField txtAddressStreet;
    private javax.swing.JTextField txtAddressZip;
    private com.toedter.calendar.JDateChooser txtDobDateChooser;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtPhoneNumberAreaCode;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

        private void nextScreen(JPanel nextScreen, String screenName) {
        WorkArea.removeAll();
        WorkArea.add(screenName , nextScreen);
        WorkArea.setAlignmentX(SwingConstants.CENTER);
        WorkArea.setAlignmentY(SwingConstants.CENTER);
        CardLayout layout = (CardLayout)WorkArea.getLayout();
        Dimension d = nextScreen.getLayout().preferredLayoutSize(nextScreen);
        WorkArea.setSize(d);
        layout.next(WorkArea); 
    }
}
