/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Dietitian.Dietitian;
import EcoSystem.EcoSystem;
import FitnessTrainer.FitnessPlan;
import FitnessTrainer.FitnessTrainer;
import Patient.Patient;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author preet
 */
public class AllFitnessPlan extends javax.swing.JPanel {
JPanel WorkArea;
EcoSystem system;
Patient p;
    /**
     * Creates new form AllFitnessPlan
     */
    public AllFitnessPlan(JPanel WorkArea,EcoSystem system,Patient p) {
        initComponents();
        this.WorkArea=WorkArea;
        this.system=system;
        this.p=p;
        report3.setVisible(false);
        DefaultTableModel model = (DefaultTableModel) fitnessplan.getModel();
        ArrayList<FitnessPlan> temp=p.getFitnessPlans();
        
        model.setRowCount(0);
        
        for(int i=0;i<temp.size();i++)
    {
        
                Object row[] = new Object[1];
                row[0] = temp.get(i);
                model.addRow(row);
    
    } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        fitnessplan = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        report3 = new javax.swing.JPanel();

        fitnessplan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "All Fitnessplan"
            }
        ));
        jScrollPane1.setViewportView(fitnessplan);

        jButton1.setText("View FitnessPlan ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("View Complete Workout data");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        report3.setBackground(new java.awt.Color(204, 255, 255));
        report3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        report3.setLayout(new javax.swing.BoxLayout(report3, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(551, 551, 551))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(report3, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))))
                .addGap(201, 201, 201))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jButton2)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(report3, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      int row = fitnessplan.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a FitnessPlan from the Table", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        FitnessPlan fp = (FitnessPlan)fitnessplan.getValueAt(row, 0);
        PatientFitnessPlan ls= new PatientFitnessPlan(WorkArea,system,p,fp);
        WorkArea.add("PatientFitnessPlan",ls);
        CardLayout layout= (CardLayout)WorkArea.getLayout();
        layout.next(WorkArea); 
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        WorkArea.remove(this);
        Component[] componentArray = WorkArea.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PatientFitnessDashboard panel = (PatientFitnessDashboard) component;
        panel.populateUpcomingFitnessTrainerAppointments();
        CardLayout layout = (CardLayout)WorkArea.getLayout();
        layout.previous(WorkArea);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        report3.setVisible(true);
        DefaultCategoryDataset dcd = new DefaultCategoryDataset();

        int cardiogiven = 0;
        int weigtgiven = 0;
        int ctgiven = 0;

        for (FitnessPlan fp : p.getFitnessPlans()) {
            for (FitnessPlan.Excercise e : fp.getExcercises()) {
                if (e.getValue().contentEquals("Cardio")) {
                    cardiogiven = cardiogiven + 1;
                } else if (e.getValue().contentEquals("CrossTraining")) {
                    ctgiven = ctgiven + 1;
                } else {
                    weigtgiven = weigtgiven + 1;
                }
            }
        }

        int cardio = 0;
        int weight = 0;
        int crosstraining = 0;
        for (FitnessPlan fp : p.getFitnessPlans()) {
            cardio = cardio + fp.getCardiotaken();
            weight = weight + fp.getWeightstaken();
            crosstraining = crosstraining + fp.getCrosstrainingtaken();

        }
        double cardiopercent = 0;
        double weightpercent = 0;
        double crosstrainingpercent = 0;
        
        
        System.out.println("cardiogive "+cardiogiven+"wg"+weigtgiven+"ctg"+ctgiven);
          System.out.println("cardio "+cardio+"w "+weight+"ctg "+crosstraining);
        try {
            cardiopercent = ((cardio * 100) / cardiogiven);
        } catch (Exception e) {
         
        }
        try {
            weightpercent = ((weight * 100) / weigtgiven);

        } catch (Exception e) {
        
        }
        try {
            crosstrainingpercent = ((crosstraining * 100) / ctgiven);
        } catch (Exception e) {
       
        }

        dcd.setValue(cardiopercent, "Excercise done", "Overall Cardio Done");
        dcd.setValue(weightpercent, "Excercise done", "Overall Weight Done");
        dcd.setValue(crosstrainingpercent, "Excercise done", "Overall CrossTraining Done");
        JFreeChart jchart = ChartFactory.createBarChart3D("Excercise Completed", "Excercise Type", "Achieved", dcd, PlotOrientation.VERTICAL, true, true, false);
        CategoryPlot plot = jchart.getCategoryPlot();
        plot.setRangeGridlinePaint(Color.black);
        ChartFrame cf = new ChartFrame("ExcerciseDone", jchart, true);
        cf.setVisible(true);
        cf.setSize(500, 400);
        ChartPanel cp = new ChartPanel(jchart);
        report3.removeAll();
        report3.add(cp);
        report3.updateUI();
        cf.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable fitnessplan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel report3;
    // End of variables declaration//GEN-END:variables
}
