/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Dietitian.Dietitian;
import EcoSystem.EcoSystem;
import FitnessTrainer.FitnessPlan;
import FitnessTrainer.FitnessTrainer;
import Patient.Patient;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author preet
 */
public class AllFitnessPlan extends javax.swing.JPanel {
JPanel WorkArea;
EcoSystem system;
Patient p;
    /**
     * Creates new form AllFitnessPlan
     */
    public AllFitnessPlan(JPanel WorkArea,EcoSystem system,Patient p) {
        initComponents();
        this.setSize(1100, 850);
        this.WorkArea=WorkArea;
        this.system=system;
        this.p=p;
        report3.setVisible(false);
        DefaultTableModel model = (DefaultTableModel) fitnessplan.getModel();
        ArrayList<FitnessPlan> temp=p.getFitnessPlans();
        
        model.setRowCount(0);
        
        for(int i=0;i<temp.size();i++)
    {
        
                Object row[] = new Object[1];
                row[0] = temp.get(i);
                model.addRow(row);
    
    } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        fitnessplan = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        report3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fitnessplan.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        fitnessplan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "All Fitness Plans"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(fitnessplan);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 118, 1000, 207));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/view_notes.png"))); // NOI18N
        jButton1.setText("View Fitness Plan ");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 343, -1, 34));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/back.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 26, 43, 27));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/view workout.png"))); // NOI18N
        jButton3.setText("View Complete Workout Data");
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 343, -1, 34));

        report3.setBackground(new java.awt.Color(204, 255, 255));
        report3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        report3.setLayout(new javax.swing.BoxLayout(report3, javax.swing.BoxLayout.LINE_AXIS));
        add(report3, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 478, 990, 317));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Fitness Plans:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Report:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 411, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/polygonal-bg1100X850.jpg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 850));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      int row = fitnessplan.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a FitnessPlan from the Table", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        FitnessPlan fp = (FitnessPlan)fitnessplan.getValueAt(row, 0);
        PatientFitnessPlan ls= new PatientFitnessPlan(WorkArea,system,p,fp);
        WorkArea.add("PatientFitnessPlan",ls);
        CardLayout layout= (CardLayout)WorkArea.getLayout();
        layout.next(WorkArea); 
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        WorkArea.remove(this);
        Component[] componentArray = WorkArea.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PatientFitnessDashboard panel = (PatientFitnessDashboard) component;
        panel.populateUpcomingFitnessTrainerAppointments();
        CardLayout layout = (CardLayout)WorkArea.getLayout();
        layout.previous(WorkArea);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        report3.setVisible(true);
        DefaultCategoryDataset dcd = new DefaultCategoryDataset();

        int cardiogiven = 0;
        int weigtgiven = 0;
        int ctgiven = 0;

        for (FitnessPlan fp : p.getFitnessPlans()) {
            for (FitnessPlan.Excercise e : fp.getExcercises()) {
                if (e.getValue().contentEquals("Cardio")) {
                    cardiogiven = cardiogiven + 1;
                } else if (e.getValue().contentEquals("CrossTraining")) {
                    ctgiven = ctgiven + 1;
                } else {
                    weigtgiven = weigtgiven + 1;
                }
            }
        }

        int cardio = 0;
        int weight = 0;
        int crosstraining = 0;
        for (FitnessPlan fp : p.getFitnessPlans()) {
            cardio = cardio + fp.getCardiotaken();
            weight = weight + fp.getWeightstaken();
            crosstraining = crosstraining + fp.getCrosstrainingtaken();

        }
        double cardiopercent = 0;
        double weightpercent = 0;
        double crosstrainingpercent = 0;
        
        
        System.out.println("cardiogive "+cardiogiven+"wg"+weigtgiven+"ctg"+ctgiven);
          System.out.println("cardio "+cardio+"w "+weight+"ctg "+crosstraining);
        try {
            cardiopercent = ((cardio * 100) / cardiogiven);
        } catch (Exception e) {
         
        }
        try {
            weightpercent = ((weight * 100) / weigtgiven);

        } catch (Exception e) {
        
        }
        try {
            crosstrainingpercent = ((crosstraining * 100) / ctgiven);
        } catch (Exception e) {
       
        }

        dcd.setValue(cardiopercent, "Excercise done", "Overall Cardio Done");
        dcd.setValue(weightpercent, "Excercise done", "Overall Weight Done");
        dcd.setValue(crosstrainingpercent, "Excercise done", "Overall CrossTraining Done");
        JFreeChart jchart = ChartFactory.createBarChart3D("Excercise Completed", "Excercise Type", "Achieved", dcd, PlotOrientation.VERTICAL, true, true, false);
        CategoryPlot plot = jchart.getCategoryPlot();
        plot.setRangeGridlinePaint(Color.black);
        ChartFrame cf = new ChartFrame("ExcerciseDone", jchart, true);
        cf.setVisible(true);
        cf.setSize(500, 400);
        ChartPanel cp = new ChartPanel(jchart);
        report3.removeAll();
        report3.add(cp);
        report3.updateUI();
        cf.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable fitnessplan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel report3;
    // End of variables declaration//GEN-END:variables
}
