/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Counselor.Counselor;
import EcoSystem.EcoSystem;
import Patient.Patient;
import javax.swing.JPanel;

/**
 *
 * @author preet
 */
public class CreateCounselingNotes extends javax.swing.JPanel {
Counselor c;
JPanel WorkArea;
EcoSystem system;
 Patient p ;
    /**
     * Creates new form CreatCounselingNotes
     */
    public CreateCounselingNotes(JPanel WorkArea,EcoSystem system,Counselor c,Patient p) {
        initComponents();
        this.WorkArea=WorkArea;
        this.system=system;
        this.p=p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 805, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 706, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
