/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Dietitian.Dietitian;
import EcoSystem.EcoSystem;
import FitnessTrainer.FitnessPlan;
import FitnessTrainer.FitnessPlan.Excercise;
import FitnessTrainer.FitnessTrainer;
import FitnessTrainer.FitnessTrainerAppointment;
import Patient.Patient;
import Personnel.PersonDetails;
import VitalSign.VitalSigns;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author preet
 */
public class CreateFitnessPlan extends javax.swing.JPanel {
JPanel WorkArea;
EcoSystem system;
FitnessTrainer f;
Patient p;
FitnessTrainerAppointment app;
    /**
     * Creates new form FitnessPlan
     */
    public CreateFitnessPlan(JPanel WorkArea,EcoSystem system,FitnessTrainer f,Patient p,FitnessTrainerAppointment app) {
      initComponents();
      this.f=f;
      initComponents();
      this.WorkArea=WorkArea;
      this.p=p;
      this.app=app;
      
      e1.setModel(new DefaultComboBoxModel(FitnessPlan.Excercise.values()));
      e2.setModel(new DefaultComboBoxModel(FitnessPlan.Excercise.values()));
      e3.setModel(new DefaultComboBoxModel(FitnessPlan.Excercise.values()));
      e4.setModel(new DefaultComboBoxModel(FitnessPlan.Excercise.values()));
      e5.setModel(new DefaultComboBoxModel(FitnessPlan.Excercise.values()));
      e6.setModel(new DefaultComboBoxModel(FitnessPlan.Excercise.values()));
      e7.setModel(new DefaultComboBoxModel(FitnessPlan.Excercise.values()));
      lblPatientname.setText(p.getPatientDetails().getFullName());
      
      
      for(FitnessTrainerAppointment f1 :f.getFitnessTrainerSchedule().getFitnessTrainerAppointments()){
      jLabel7.setText(f1.getInjuries());
      jLabel5.setText(f1.getPatientMedication());
      jLabel3.setText(f1.getCheifcomplaints());
      
      }
      showmostrecentVitalSign();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtmeal7 = new javax.swing.JEditorPane();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtmeal2 = new javax.swing.JEditorPane();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtmeal4 = new javax.swing.JEditorPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtmeal6 = new javax.swing.JEditorPane();
        jButton2 = new javax.swing.JButton();
        lblPatientname = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtmeal1 = new javax.swing.JEditorPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtmeal5 = new javax.swing.JEditorPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVitalSign = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtmeal3 = new javax.swing.JEditorPane();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        e2 = new javax.swing.JComboBox<>();
        e4 = new javax.swing.JComboBox<>();
        e1 = new javax.swing.JComboBox<>();
        e5 = new javax.swing.JComboBox<>();
        e6 = new javax.swing.JComboBox<>();
        e3 = new javax.swing.JComboBox<>();
        e7 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/day7.png"))); // NOI18N
        jLabel11.setText("Day 7:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 730, 137, 50));

        jScrollPane5.setViewportView(txtmeal7);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 730, 366, 52));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/day3.png"))); // NOI18N
        jLabel10.setText("Day 3:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 137, 50));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/day2.png"))); // NOI18N
        jLabel9.setText("Day 2:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 137, 50));

        jScrollPane4.setViewportView(txtmeal2);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 366, 52));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/day4.png"))); // NOI18N
        jLabel8.setText("Day 4:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 137, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/day1.png"))); // NOI18N
        jLabel2.setText("Day 1:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 130, 50));

        jScrollPane3.setViewportView(txtmeal4);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, 366, 52));

        jScrollPane8.setViewportView(txtmeal6);

        add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 670, 366, 52));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/back.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 26, 35, 25));

        lblPatientname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        add(lblPatientname, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 19, 242, 30));

        jScrollPane2.setViewportView(txtmeal1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 366, 52));

        jScrollPane7.setViewportView(txtmeal5);

        add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 600, 366, 52));

        tblVitalSign.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Recorded Date", "Blood Pressure", "Heart Rate", "Respiratory Rate", "Weight"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVitalSign);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 63, 760, 90));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/day6.png"))); // NOI18N
        jLabel13.setText("Day 6:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 670, 137, 50));

        jScrollPane6.setViewportView(txtmeal3);

        add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 366, 52));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/day5.png"))); // NOI18N
        jLabel12.setText("Day 5:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, 137, 50));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/icons8-weightlifting-30.png"))); // NOI18N
        jButton1.setText("Create Fitness  Regime");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 790, 220, 39));

        add(e2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, 160, -1));

        add(e4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 540, 160, -1));

        e1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        add(e1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 160, -1));

        add(e5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 610, 160, -1));

        add(e6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 680, 160, -1));

        add(e3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 470, 160, -1));

        add(e7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 740, 160, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/icons8-complaint-30.png"))); // NOI18N
        jLabel1.setText("Chief Complaint");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 171, 150, 27));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jLabel3.setOpaque(true);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 171, 360, 27));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/medication.png"))); // NOI18N
        jLabel4.setText("Medication");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 226, 140, 27));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jLabel5.setOpaque(true);
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 226, 360, 27));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/health.png"))); // NOI18N
        jLabel6.setText("Health Conditions");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 282, 150, 27));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jLabel7.setOpaque(true);
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 282, 360, 27));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setText("Fitness Plan for");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 19, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/polygonal-bg1100X850.jpg"))); // NOI18N
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 1100, 860));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        WorkArea.remove(this);
        Component[] componentArray = WorkArea.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout)WorkArea.getLayout();
        FitnessTrainerDashBoard fp= (FitnessTrainerDashBoard)component;
        fp.populateupcomingAppointments();
        layout.previous(WorkArea);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
              ArrayList<String> fitnessplan =new ArrayList<>();
       ArrayList<Excercise> excercise=new ArrayList<>();
        fitnessplan.add(txtmeal1.getText());
        fitnessplan.add(txtmeal2.getText());
        fitnessplan.add(txtmeal3.getText());
        fitnessplan.add(txtmeal4.getText());
        fitnessplan.add(txtmeal5.getText());
        fitnessplan.add(txtmeal6.getText());
        fitnessplan.add(txtmeal7.getText());
        Excercise ex1=(Excercise)e1.getSelectedItem();
        Excercise ex2=(Excercise)e2.getSelectedItem();
        Excercise ex3=(Excercise)e3.getSelectedItem();
        Excercise ex4=(Excercise)e4.getSelectedItem();
        Excercise ex5=(Excercise)e5.getSelectedItem();
        Excercise ex6=(Excercise)e6.getSelectedItem();
        Excercise ex7=(Excercise)e7.getSelectedItem();
        excercise.add(ex1);
          excercise.add(ex2);
            excercise.add(ex3);
              excercise.add(ex4);
                excercise.add(ex5);
                  excercise.add(ex6);
                    excercise.add(ex7);
        f.addFitnessPlan(p, fitnessplan,excercise);
        app.setDone(Boolean.TRUE);
        JOptionPane.showMessageDialog(this, "Weekly Fitness Regime has been Created for  "+p.getPatientDetails().getFullName());    
        WorkArea.remove(this);
        Component[] componentArray = WorkArea.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout)WorkArea.getLayout();
        FitnessTrainerDashBoard fp= (FitnessTrainerDashBoard)component;
        fp.populateupcomingAppointments();
        layout.previous(WorkArea);
        } catch (Exception e) {
            
             JOptionPane.showMessageDialog(this, "please fill in all details correctly  ");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

 private void showmostrecentVitalSign() {
 DefaultTableModel model = (DefaultTableModel) tblVitalSign.getModel();
 
     try {
         VitalSigns temp=p.getMostRecentVitalSigns(); 
 model.setRowCount(0);       
 Object row[] = new Object[5];
                row[0] = temp.getDateForVitalSigns();
                row[1] = temp.getBloodPressure();
                row[2] = temp.getHeartRate();
                row[3] = temp.getRespiratoryRate();
                row[4] = temp.getWeight();
                model.addRow(row);
   
     } catch (Exception e) {
          JOptionPane.showMessageDialog(this, "Patient has not recorded his vitalSigns yet");
          return;
     }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Excercise> e1;
    private javax.swing.JComboBox<Excercise> e2;
    private javax.swing.JComboBox<Excercise> e3;
    private javax.swing.JComboBox<Excercise> e4;
    private javax.swing.JComboBox<Excercise> e5;
    private javax.swing.JComboBox<Excercise> e6;
    private javax.swing.JComboBox<Excercise> e7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel lblPatientname;
    private javax.swing.JTable tblVitalSign;
    private javax.swing.JEditorPane txtmeal1;
    private javax.swing.JEditorPane txtmeal2;
    private javax.swing.JEditorPane txtmeal3;
    private javax.swing.JEditorPane txtmeal4;
    private javax.swing.JEditorPane txtmeal5;
    private javax.swing.JEditorPane txtmeal6;
    private javax.swing.JEditorPane txtmeal7;
    // End of variables declaration//GEN-END:variables
}
