/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.PSysAdminRole;


import DeliveryMan.DeliveryMan;
import DeliveryMan.DeliveryManDirectory;
import EcoSystem.EcoSystem;
import Personnel.Address;
import Personnel.Person;
import Personnel.PersonDetails;
import Personnel.Role;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sravya
 */
public class UpdateDeliveryManJPanel extends javax.swing.JPanel {

    private JPanel workArea; 
    private EcoSystem ecoSystem; 
    private DeliveryMan deliveryMan;

    public UpdateDeliveryManJPanel(
            JPanel workArea, 
            EcoSystem ecoSystem,
            DeliveryMan deliveryMan) {
        
        
        this.workArea = workArea;
        this.ecoSystem = ecoSystem;
        this.deliveryMan = deliveryMan;
        initComponents();
        txtUpdateDelManName.setText(deliveryMan.getPersonDetails().getFullName());
        txtUpdateDelManPhNo.setText(deliveryMan.getPersonDetails().getPhoneNumber());
        txtUpdateDelManBuildingNo.setText(deliveryMan.getPersonDetails().getAddress().getApartment());
        txtUpdateDelManSt.setText(deliveryMan.getPersonDetails().getAddress().getStreet());
        txtUpdateDelManCity.setText(deliveryMan.getPersonDetails().getAddress().getCity());
        txtUpdateDelManZIP.setText(deliveryMan.getPersonDetails().getAddress().getZipcode());
        txtUpdateDelManState.setText(deliveryMan.getPersonDetails().getAddress().getState());
        txtUpdateDelManCountry.setText(deliveryMan.getPersonDetails().getAddress().getCountry());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtUpdateDelManName = new javax.swing.JTextField();
        lblDOB = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblBuildingNo = new javax.swing.JLabel();
        txtUpdateDelManBuildingNo = new javax.swing.JTextField();
        lblDOB1 = new javax.swing.JLabel();
        txtUpdateDelManSt = new javax.swing.JTextField();
        lblName2 = new javax.swing.JLabel();
        txtUpdateDelManCity = new javax.swing.JTextField();
        lblZIP = new javax.swing.JLabel();
        txtUpdateDelManZIP = new javax.swing.JTextField();
        lblName3 = new javax.swing.JLabel();
        txtUpdateDelManCountry = new javax.swing.JTextField();
        lblZIP1 = new javax.swing.JLabel();
        txtUpdateDelManPhNo = new javax.swing.JTextField();
        lblZIP2 = new javax.swing.JLabel();
        txtUpdateDelManState = new javax.swing.JTextField();
        jDateChooserUpdateDelManDOB = new com.toedter.calendar.JDateChooser();
        cmbUpdateDelManGender = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.setToolTipText("Back");
        btnBack.setContentAreaFilled(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 45, 69, 33));

        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-save-64.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.setContentAreaFilled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 690, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Update Delivery Man Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 46, -1, -1));

        lblName.setText("Name:");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));
        add(txtUpdateDelManName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 200, -1));

        lblDOB.setText("DOB:");
        add(lblDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        jLabel2.setText("Gender:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        lblBuildingNo.setText("Building No:");
        add(lblBuildingNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));
        add(txtUpdateDelManBuildingNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 200, -1));

        lblDOB1.setText("Street");
        add(lblDOB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, -1, -1));
        add(txtUpdateDelManSt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 200, -1));

        lblName2.setText("City");
        add(lblName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, -1));
        add(txtUpdateDelManCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 200, -1));

        lblZIP.setText("ZIP");
        add(lblZIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, -1, -1));
        add(txtUpdateDelManZIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 200, -1));

        lblName3.setText("Country");
        add(lblName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, -1, -1));
        add(txtUpdateDelManCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, 200, -1));

        lblZIP1.setText("Phone Number:");
        add(lblZIP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 630, -1, -1));
        add(txtUpdateDelManPhNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 620, 200, -1));

        lblZIP2.setText("State");
        add(lblZIP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, -1, -1));
        add(txtUpdateDelManState, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 200, -1));
        add(jDateChooserUpdateDelManDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 210, -1));

        add(cmbUpdateDelManGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 200, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        Component[] componentArray = workArea.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageDeliveryManJPanel mdmjp = (ManageDeliveryManJPanel) component;
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if( txtUpdateDelManName.getText().isEmpty() ||
            txtUpdateDelManBuildingNo.getText().isEmpty() || 
            txtUpdateDelManSt.getText().isEmpty() || 
            txtUpdateDelManCity.getText().isEmpty() || 
            txtUpdateDelManZIP.getText().isEmpty() || 
            txtUpdateDelManState.getText().isEmpty() || 
            txtUpdateDelManCountry.getText().isEmpty() || 
            txtUpdateDelManPhNo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Fields cannot be left empty");
            return;
        }

        boolean flag ;

        String phoneNumber = txtUpdateDelManPhNo.getText();

        if(phoneNumber.length() != 10) {
            JOptionPane.showMessageDialog(null, "PhoneNumber must be of 10 digits");
            return;
        }
        
        flag = phoneNumber.matches("^[0-9]+$");
        if(!flag) {
            JOptionPane.showMessageDialog(null, "Phone Number must contain only digits ");
            return;
        }
        
        for(Person p : ecoSystem.globalUserDirectory.getByRole(Role.DELIVERY_MAN)) {
            if(deliveryMan != p && p.getPersonDetails().getPhoneNumber().equals(phoneNumber)) {
                JOptionPane.showMessageDialog(null, "Phone Number already exists");
            }
        }
        String apartment = txtUpdateDelManBuildingNo.getText();
        String street = txtUpdateDelManSt.getText();
        String city = txtUpdateDelManCity.getText();
        String zipcode = txtUpdateDelManZIP.getText();
        String state = txtUpdateDelManState.getText();
        String country = txtUpdateDelManCountry.getText();

        deliveryMan.getPersonDetails().setPhoneNumber(phoneNumber); //add setters in Person details and Address classes
        deliveryMan.getPersonDetails().setAddress(new Address(street, apartment, city, zipcode, state, country));
        deliveryMan.getPersonDetails().setFullName(txtUpdateDelManName.getText());

        JOptionPane.showMessageDialog(null, "Delivery Man Profile Updated");
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbUpdateDelManGender;
    private com.toedter.calendar.JDateChooser jDateChooserUpdateDelManDOB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBuildingNo;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDOB1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblZIP;
    private javax.swing.JLabel lblZIP1;
    private javax.swing.JLabel lblZIP2;
    private javax.swing.JTextField txtUpdateDelManBuildingNo;
    private javax.swing.JTextField txtUpdateDelManCity;
    private javax.swing.JTextField txtUpdateDelManCountry;
    private javax.swing.JTextField txtUpdateDelManName;
    private javax.swing.JTextField txtUpdateDelManPhNo;
    private javax.swing.JTextField txtUpdateDelManSt;
    private javax.swing.JTextField txtUpdateDelManState;
    private javax.swing.JTextField txtUpdateDelManZIP;
    // End of variables declaration//GEN-END:variables
}
