/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UICounselorDietitianFitnessTrainer;

import Dietitian.DietPlan;
import EcoSystem.EcoSystem;
import FitnessTrainer.FitnessPlan;
import FitnessTrainer.FitnessPlan.Excercise;
import Patient.Patient;
import java.awt.CardLayout;
import java.awt.Color;
import static java.awt.Color.white;
import java.awt.Component;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author preet
 */
public class PatientFitnessPlan extends javax.swing.JPanel {

    JPanel WorkArea;
    EcoSystem system;
    Patient p;
    ArrayList<Excercise> temp2;
    FitnessPlan fp;
    int cardio = 0;
    int weight = 0;
    int crosstraining = 0;

    /**
     * Creates new form ViewFitnessPlan
     */
    public PatientFitnessPlan(JPanel WorkArea, EcoSystem system, Patient p,FitnessPlan fp) {
        initComponents();
        this.WorkArea = WorkArea;
        this.system = system;
        this.p = p;
        this.fp=fp;
        report3.setVisible(false);
        lblpatientname.setText("HI  " + p.getPatientDetails().getFullName());
        //for (FitnessTrainer.FitnessPlan fp : p.getFitnessPlans()) {
            ArrayList<String> temp = new ArrayList();
            temp = fp.getFitnessplans();
            txtmeal1.setText(temp.get(0));
            txtmeal2.setText(temp.get(1));
            txtmeal3.setText(temp.get(2));
            txtmeal4.setText(temp.get(3));
            txtmeal5.setText(temp.get(4));
            txtmeal6.setText(temp.get(5));
            txtmeal7.setText(temp.get(6));

            temp2 = fp.getExcercises();
            System.out.println("ssssssss" + temp2);
            e1.setText(temp2.get(0).getValue());
            e2.setText(temp2.get(1).getValue());
            e3.setText(temp2.get(2).getValue());
            e4.setText(temp2.get(3).getValue());
            e5.setText(temp2.get(4).getValue());
            e6.setText(temp2.get(5).getValue());
            e7.setText(temp2.get(6).getValue());

            for (Excercise e : fp.getExcercises()) {
                if (e.getValue().contentEquals("Cardio")) {
                    cardio = cardio + 1;
                } else if (e.getValue().contentEquals("CrossTraining")) {
                    crosstraining = crosstraining + 1;
                } else {
                    weight = weight + 1;
                }
            }

       // }

        populatechart();
        populateTrackMyFitnessChart();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtmeal5 = new javax.swing.JEditorPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtmeal2 = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtmeal1 = new javax.swing.JEditorPane();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblPatientname = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtmeal7 = new javax.swing.JEditorPane();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtmeal6 = new javax.swing.JEditorPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtmeal3 = new javax.swing.JEditorPane();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtmeal4 = new javax.swing.JEditorPane();
        jLabel2 = new javax.swing.JLabel();
        lblpatientname = new javax.swing.JLabel();
        report1 = new javax.swing.JPanel();
        c1 = new javax.swing.JCheckBox();
        c2 = new javax.swing.JCheckBox();
        c3 = new javax.swing.JCheckBox();
        c4 = new javax.swing.JCheckBox();
        c5 = new javax.swing.JCheckBox();
        c6 = new javax.swing.JCheckBox();
        c7 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        report3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        e1 = new javax.swing.JTextField();
        e2 = new javax.swing.JTextField();
        e3 = new javax.swing.JTextField();
        e4 = new javax.swing.JTextField();
        e5 = new javax.swing.JTextField();
        e6 = new javax.swing.JTextField();
        e7 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/day4.png"))); // NOI18N
        jLabel8.setText("Day 4:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 137, 50));

        jScrollPane7.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane7.setDoubleBuffered(true);
        jScrollPane7.setEnabled(false);

        txtmeal5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtmeal5.setEnabled(false);
        jScrollPane7.setViewportView(txtmeal5);

        add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 630, 366, 52));

        jScrollPane4.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane4.setDoubleBuffered(true);
        jScrollPane4.setEnabled(false);

        txtmeal2.setBackground(new java.awt.Color(255, 255, 255));
        txtmeal2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtmeal2.setEnabled(false);
        jScrollPane4.setViewportView(txtmeal2);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 366, 52));

        jScrollPane2.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setDoubleBuffered(true);
        jScrollPane2.setEnabled(false);

        txtmeal1.setBackground(new java.awt.Color(255, 255, 255));
        txtmeal1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtmeal1.setEnabled(false);
        jScrollPane2.setViewportView(txtmeal1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 366, 52));

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/day2.png"))); // NOI18N
        jLabel9.setText("Day 2:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 430, 140, 50));

        jLabel10.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/day3.png"))); // NOI18N
        jLabel10.setText("Day 3:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 137, 50));

        lblPatientname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        add(lblPatientname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 242, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/back.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 30));

        jLabel12.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/day5.png"))); // NOI18N
        jLabel12.setText("Day 5:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, 137, 50));

        jScrollPane5.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane5.setDoubleBuffered(true);
        jScrollPane5.setEnabled(false);

        txtmeal7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtmeal7.setEnabled(false);
        jScrollPane5.setViewportView(txtmeal7);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 770, 366, 52));

        jLabel11.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/day7.png"))); // NOI18N
        jLabel11.setText("Day 7:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 770, 137, 50));

        jScrollPane8.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane8.setDoubleBuffered(true);
        jScrollPane8.setEnabled(false);

        txtmeal6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtmeal6.setEnabled(false);
        jScrollPane8.setViewportView(txtmeal6);

        add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 700, 366, 52));

        jScrollPane6.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane6.setDoubleBuffered(true);
        jScrollPane6.setEnabled(false);

        txtmeal3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtmeal3.setEnabled(false);
        jScrollPane6.setViewportView(txtmeal3);

        add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 366, 52));

        jLabel13.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/day6.png"))); // NOI18N
        jLabel13.setText("Day 6:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 700, 137, 50));

        jScrollPane3.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane3.setDoubleBuffered(true);
        jScrollPane3.setEnabled(false);

        txtmeal4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtmeal4.setEnabled(false);
        jScrollPane3.setViewportView(txtmeal4);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 366, 52));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/day1.png"))); // NOI18N
        jLabel2.setText("Day 1:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 137, 50));

        lblpatientname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add(lblpatientname, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 8, 265, 40));

        report1.setBackground(new java.awt.Color(204, 255, 255));
        report1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        report1.setLayout(new javax.swing.BoxLayout(report1, javax.swing.BoxLayout.LINE_AXIS));
        add(report1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 371, 277));

        c1.setMaximumSize(new java.awt.Dimension(22, 22));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, -1, -1));
        add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, -1, -1));

        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });
        add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, -1, -1));
        add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 570, -1, -1));
        add(c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 640, -1, -1));
        add(c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 710, -1, -1));
        add(c7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 780, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Mark Your Goals");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, -1, -1));

        report3.setBackground(new java.awt.Color(204, 255, 255));
        report3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        report3.setLayout(new javax.swing.BoxLayout(report3, javax.swing.BoxLayout.LINE_AXIS));
        add(report3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 360, 277));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/icons8-graph-report-30.png"))); // NOI18N
        jButton1.setText("Generate My Weekly Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, 38));

        e1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        e1.setEnabled(false);
        e1.setOpaque(true);
        add(e1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 84, 42));

        e2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        e2.setEnabled(false);
        add(e2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, 84, 42));

        e3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        e3.setEnabled(false);
        add(e3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, 84, 42));

        e4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        e4.setEnabled(false);
        add(e4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 560, 84, 42));

        e5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        e5.setEnabled(false);
        add(e5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 630, 84, 42));

        e6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        e6.setEnabled(false);
        add(e6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 700, 84, 42));

        e7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        e7.setEnabled(false);
        add(e7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 770, 84, 42));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/polygonal-bg1100X850.jpg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 6, 1100, 840));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        WorkArea.remove(this);
        Component[] componentArray = WorkArea.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) WorkArea.getLayout();
        layout.previous(WorkArea);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed


    }//GEN-LAST:event_c1ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        report3.setVisible(true);
        populateTrackMyFitnessChart();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox c1;
    private javax.swing.JCheckBox c2;
    private javax.swing.JCheckBox c3;
    private javax.swing.JCheckBox c4;
    private javax.swing.JCheckBox c5;
    private javax.swing.JCheckBox c6;
    private javax.swing.JCheckBox c7;
    private javax.swing.JTextField e1;
    private javax.swing.JTextField e2;
    private javax.swing.JTextField e3;
    private javax.swing.JTextField e4;
    private javax.swing.JTextField e5;
    private javax.swing.JTextField e6;
    private javax.swing.JTextField e7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel lblPatientname;
    private javax.swing.JLabel lblpatientname;
    private javax.swing.JPanel report1;
    private javax.swing.JPanel report3;
    private javax.swing.JEditorPane txtmeal1;
    private javax.swing.JEditorPane txtmeal2;
    private javax.swing.JEditorPane txtmeal3;
    private javax.swing.JEditorPane txtmeal4;
    private javax.swing.JEditorPane txtmeal5;
    private javax.swing.JEditorPane txtmeal6;
    private javax.swing.JEditorPane txtmeal7;
    // End of variables declaration//GEN-END:variables

    private void populatechart() {
        double cardiopercent = 0;
        double weightpercent = 0;
        double crosstrainingpercent = 0;

        
        cardiopercent = ((cardio * 100) / 7);

        weightpercent = ((weight * 100) / 7);

        crosstrainingpercent = ((crosstraining * 100) / 7);

        DefaultPieDataset dcd = new DefaultPieDataset();
        dcd.setValue("Cardio Percent", cardiopercent);
        dcd.setValue("Weights Percent", weightpercent);
        dcd.setValue("CrossTraining Percent", crosstrainingpercent);
        JFreeChart jchart = ChartFactory.createPieChart3D("Percentage of Daily Recommended Fitness Routine", dcd, true, true, true);
        PiePlot piechrt = (PiePlot) jchart.getPlot();
        piechrt.setBackgroundPaint(white);
        ChartFrame cf = new ChartFrame("Percentage of Daily Recommended Fitness Routine", jchart);
        cf.setVisible(true);
        cf.setSize(500, 400);
        ChartPanel cp = new ChartPanel(jchart);
        report1.removeAll();
        report1.add(cp);
        report1.updateUI();
        cf.dispose();
    }

    private void populateTrackMyFitnessChart() {
        int checkcardio = 0;
        int checkweight = 0;
        int checkcrosstraining = 0;
        if (c1.isSelected()) {
            if (e1.getText().equals(FitnessTrainer.FitnessPlan.Excercise.Cardio.toString())) {
                checkcardio = checkcardio + 1;
            } else if (e1.getText().equals(FitnessTrainer.FitnessPlan.Excercise.Weight.toString())) {
                checkweight = checkweight + 1;
            } else {
                checkcrosstraining = checkcrosstraining + 1;
            }
        }

        if (c2.isSelected()) {
            if (e2.getText().equals(FitnessTrainer.FitnessPlan.Excercise.Cardio.toString())) {
                checkcardio = checkcardio + 1;
            } else if (e2.getText().equals(FitnessTrainer.FitnessPlan.Excercise.Weight.toString())) {
                checkweight = checkweight + 1;
            } else {
                checkcrosstraining = checkcrosstraining + 1;
            }
        }

        if (c3.isSelected()) {
            if (e3.getText().equals(FitnessTrainer.FitnessPlan.Excercise.Cardio.toString())) {
                checkcardio = checkcardio + 1;
            } else if (e3.getText().equals(FitnessTrainer.FitnessPlan.Excercise.Weight.toString())) {
                checkweight = checkweight + 1;
            } else {
                checkcrosstraining = checkcrosstraining + 1;
            }
        }

        if (c4.isSelected()) {
            if (e4.getText().equals(FitnessTrainer.FitnessPlan.Excercise.Cardio.toString())) {
                checkcardio = checkcardio + 1;
            } else if (e4.getText().equals(FitnessTrainer.FitnessPlan.Excercise.Weight.toString())) {
                checkweight = checkweight + 1;
            } else {
                checkcrosstraining = checkcrosstraining + 1;
            }
        }

        if (c5.isSelected()) {
            if (e5.getText().equals(FitnessTrainer.FitnessPlan.Excercise.Cardio.toString())) {
                checkcardio = checkcardio + 1;
            } else if (e5.getText().equals(FitnessTrainer.FitnessPlan.Excercise.Weight.toString())) {
                checkweight = checkweight + 1;
            } else {
                checkcrosstraining = checkcrosstraining + 1;
            }
        }

        if (c6.isSelected()) {
            if (e6.getText().equals(FitnessTrainer.FitnessPlan.Excercise.Cardio.toString())) {
                checkcardio = checkcardio + 1;
            } else if (e6.getText().equals(FitnessTrainer.FitnessPlan.Excercise.Weight.toString())) {
                checkweight = checkweight + 1;
            } else {
                checkcrosstraining = checkcrosstraining + 1;
            }
        }

        if (c7.isSelected()) {
            if (e7.getText().equals(FitnessTrainer.FitnessPlan.Excercise.Cardio.toString())) {
                checkcardio = checkcardio + 1;
            } else if (e7.getText().equals(FitnessTrainer.FitnessPlan.Excercise.Weight.toString())) {
                checkweight = checkweight + 1;
            } else {
                checkcrosstraining = checkcrosstraining + 1;
            }
        }
        System.out.println("cardio = " + cardio);
        //Add Graph Details
        int cardiopercent = 0;
        int weightpercent = 0;
        int crosstrainingpercent = 0;

        if (cardio == 0) {
            cardiopercent = 0;
        } else {
            cardiopercent = ((checkcardio * 100) / cardio);
        }
        if (weight == 0) {
            weightpercent = 0;
        } else {
            weightpercent = ((checkweight * 100) / weight);
        }
        if (crosstraining == 0) {
            crosstrainingpercent = 0;
        } else {
            crosstrainingpercent = ((checkcrosstraining * 100) / crosstraining);
        }

        fp.setCardiotaken(checkcardio);
        fp.setCrosstrainingtaken(checkcrosstraining);
        fp.setWeightstaken(checkweight);
        
        System.out.println("cardiopercent" + cardiopercent + "weightpercent " + weightpercent + "ctpecent " + crosstrainingpercent);
        DefaultCategoryDataset dcd = new DefaultCategoryDataset();

        dcd.setValue(cardiopercent, "Excercise done", "Cardio Done");
        dcd.setValue(weightpercent, "Excercise done", "Weight Done");
        dcd.setValue(crosstrainingpercent, "Excercise done", "CrossTraining Done");
        JFreeChart jchart = ChartFactory.createBarChart3D("Excercise Completed", "Excercise Type", "Achieved", dcd, PlotOrientation.VERTICAL, true, true, false);
        CategoryPlot plot = jchart.getCategoryPlot();
        plot.setRangeGridlinePaint(Color.black);
        ChartFrame cf = new ChartFrame("ExcerciseDone", jchart, true);
        cf.setVisible(true);
        cf.setSize(500, 400);
        ChartPanel cp = new ChartPanel(jchart);
        report3.removeAll();
        report3.add(cp);
        report3.updateUI();
        cf.dispose();
    }
}
