/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UICounselorDietitianFitnessTrainer;

import Dietitian.DietitianAppointment;
import EcoSystem.EcoSystem;
import FitnessTrainer.FitnessTrainerAppointment;
import Patient.Patient;
import UIPatientDoctorInsuranceProvider.PatientHomePagePanel;
import Utils.NextScreen;
import java.awt.CardLayout;
import java.awt.Component;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
//import static sun.tools.jconsole.LabeledComponent.layout;

/**
 *
 * @author preet
 */
public class PatientFitnessDashboard extends javax.swing.JPanel implements NextScreen {
JPanel WorkArea;
   EcoSystem system;
   Patient p ;
    /**
     * Creates new form PatientFitnessDashboard
     */
    public PatientFitnessDashboard(JPanel WorkArea,EcoSystem system,Patient p ) {
        initComponents();
        this.setSize(1100,850);
           this.WorkArea=WorkArea;
        this.system=system;
        this.p=p;
        populateUpcomingFitnessTrainerAppointments();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        UpcomingFitnessAppointments = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/calendar.png"))); // NOI18N
        jButton1.setText("Book Appointment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 200, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/view_past_appointment.png"))); // NOI18N
        jButton2.setText("View Past Appointment");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 220, -1));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/view_notes.png"))); // NOI18N
        jButton4.setText("View Fitness Videos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 200, 40));

        UpcomingFitnessAppointments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FitnessTrainer Name", "Upcoming Appointment Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(UpcomingFitnessAppointments);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 88, 860, 197));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/back.png"))); // NOI18N
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 26, -1, -1));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/icons8-weightlifting-30.png"))); // NOI18N
        jButton5.setText("View All Fitness Plan");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, 210, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Fitness Trainer Dashboard");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 22, 306, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/polygonal-bg1100X850.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 850));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PatientBookAnAppointment ls= new PatientBookAnAppointment(WorkArea,system,p,2);
        WorkArea.add("PatientBookAppointment",ls);
        CardLayout layout= (CardLayout)WorkArea.getLayout();
        layout.next(WorkArea);  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ViewPastAppointmentFitness ls= new ViewPastAppointmentFitness(WorkArea,system,p.getFitnessTrainerAppointments(),0);
        WorkArea.add("ViewPastAppointmentFitness",ls);
        CardLayout layout= (CardLayout)WorkArea.getLayout();
        layout.next(WorkArea); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
//        WorkArea.remove(this);
//        Component[] componentArray = WorkArea.getComponents();
//        Component component = componentArray[componentArray.length - 1];
//         PatientHomePagePanel d=(PatientHomePagePanel)component;
//        d.populatefitnessappointments();
//        CardLayout layout = (CardLayout)WorkArea.getLayout();
//        layout.previous(WorkArea);
        nextScreen(WorkArea, new PatientHomePagePanel(WorkArea, system, p), "PatientHomePagePanel");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         FitnessVideo fv= new FitnessVideo(WorkArea,system,p);
        WorkArea.add("FitnessVideo",fv);
        CardLayout layout= (CardLayout)WorkArea.getLayout();
        layout.next(WorkArea);  
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
  
       AllFitnessPlan f= new AllFitnessPlan(WorkArea,system,p);
        WorkArea.add("AllFitnessPlan",f);
        CardLayout layout= (CardLayout)WorkArea.getLayout();
        layout.next(WorkArea);  
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable UpcomingFitnessAppointments;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
   
    public void populateUpcomingFitnessTrainerAppointments() {
      
 DefaultTableModel model = (DefaultTableModel) UpcomingFitnessAppointments.getModel();
 ArrayList<FitnessTrainerAppointment> temp=new ArrayList();
        try {
            temp=p.getFitnessTrainerAppointments();
        } catch (Exception e) {
            return;
        }
 
 model.setRowCount(0);
        
        for(int i=0;i<temp.size();i++)
    {
        if(temp.get(i).getDate().isAfter(LocalDate.now())&& temp.get(i).getDone()==false){
                Object row[] = new Object[2];
                row[0] = temp.get(i).getFitnessTrainer().getFitnessTrainerDetails().getFullName();
                row[1] = temp.get(i).getDate();
                model.addRow(row);
    }
    }   

  
    }





}
