/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Utils;

import EcoSystem.EcoSystem;
import Personnel.Person;
import java.awt.Color;
import java.time.Instant;
import java.util.Date;
import java.util.Random;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.apache.commons.lang.StringUtils;

/**
 *
 * @author mrs.katey
 */
public class ForgetPasswordJPanel extends javax.swing.JPanel {

    FieldsValidator fieldsValidator = new FieldsValidator();
    EcoSystem ecoSystem;
    ButtonGroup buttonGroup = new ButtonGroup();
    Random rnd = new Random();
    
    String sentOtp = null;
    
    Person selectedPerson;
    /**
     * Creates new form ForgetPasswordJPanel
     */
    public ForgetPasswordJPanel(EcoSystem ecoSystem) {
        initComponents();
        this.ecoSystem = ecoSystem;
        
        buttonGroup.add(jRadioButtonSelectEmail);
        buttonGroup.add(jRadioButtonSelectMobileNumber);
        
        jTextFieldMobileNumberCountryCode.setEnabled(false);
        jRadioButtonSelectEmail.setEnabled(false);
        jRadioButtonSelectMobileNumber.setEnabled(false);
        
        jTextFieldEmailId.setEnabled(false);
        jTextFieldMobileNum.setEnabled(false);
        jButtonSendOTP.setEnabled(false);
        jTextFieldEnterOTP.setEnabled(false);
        jButtonCheckOTP.setEnabled(false);

        jTextFieldNewPassword.setEnabled(false);
        jTextConfirmPassword.setEnabled(false);
        jButtonResetPassword.setEnabled(false);
        
        jLabelUsernameCheck.setText("");
        jLabelOTPCheck.setText("");
        jLabelEmailIdCheck.setText("");
        jLabelPhoneNumberCheck.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldUserName = new javax.swing.JTextField();
        jRadioButtonSelectEmail = new javax.swing.JRadioButton();
        jRadioButtonSelectMobileNumber = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabelUsernameCheck = new javax.swing.JLabel();
        jTextFieldEnterOTP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonSendOTP = new javax.swing.JButton();
        jButtonCheckOTP = new javax.swing.JButton();
        jButtonCheckUserName1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabelOTPCheck = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonResetPassword = new javax.swing.JButton();
        jTextFieldMobileNumberCountryCode = new javax.swing.JTextField();
        jTextFieldEmailId = new javax.swing.JTextField();
        jTextFieldMobileNum = new javax.swing.JTextField();
        jLabelPhoneNumberCheck = new javax.swing.JLabel();
        jLabelEmailIdCheck = new javax.swing.JLabel();
        jTextFieldNewPassword = new javax.swing.JPasswordField();
        jTextConfirmPassword = new javax.swing.JPasswordField();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        jLabel1.setText("Password Reset Tool");

        jLabel2.setText("Select Email OR Mobile number to recieve a one time OPT to reset password");

        jRadioButtonSelectEmail.setText("Email ");
        jRadioButtonSelectEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSelectEmailActionPerformed(evt);
            }
        });

        jRadioButtonSelectMobileNumber.setText("Mobile number");
        jRadioButtonSelectMobileNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSelectMobileNumberActionPerformed(evt);
            }
        });

        jLabel3.setText("Enter the one time OTP  you recieved");

        jLabelUsernameCheck.setText("Verified");

        jLabel4.setText("Enter your username");

        jButtonSendOTP.setText("Send OTP");
        jButtonSendOTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendOTPActionPerformed(evt);
            }
        });

        jButtonCheckOTP.setText("Go");
        jButtonCheckOTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckOTPActionPerformed(evt);
            }
        });

        jButtonCheckUserName1.setText("Go");
        jButtonCheckUserName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckUserName1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Enter new Password");

        jLabelOTPCheck.setText("Verified!");

        jLabel6.setText("Confirm password");

        jButtonResetPassword.setText("Reset Password");
        jButtonResetPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetPasswordActionPerformed(evt);
            }
        });

        jTextFieldMobileNumberCountryCode.setText("+1");

        jLabelPhoneNumberCheck.setText("Verified");

        jLabelEmailIdCheck.setText("Verified");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonCheckUserName1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelUsernameCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonSelectMobileNumber)
                                    .addComponent(jRadioButtonSelectEmail))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelEmailIdCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldMobileNumberCountryCode, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldMobileNum, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSendOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldEnterOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCheckOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelOTPCheck, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextConfirmPassword))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jButtonResetPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelPhoneNumberCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCheckUserName1)
                    .addComponent(jLabelUsernameCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSelectEmail)
                    .addComponent(jTextFieldEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmailIdCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSelectMobileNumber)
                    .addComponent(jTextFieldMobileNumberCountryCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMobileNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPhoneNumberCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonSendOTP)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEnterOTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCheckOTP)
                    .addComponent(jLabelOTPCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButtonResetPassword)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 815, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 649, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonSelectEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSelectEmailActionPerformed
        // TODO add your handling code here:
        jTextFieldEmailId.setEnabled(true);
        jRadioButtonSelectEmail.setEnabled(true);
        jRadioButtonSelectMobileNumber.setEnabled(true);
        
         jButtonSendOTP.setEnabled(true);
        jLabelEmailIdCheck.setText("");
        jLabelPhoneNumberCheck.setText("");
        
        jTextFieldMobileNumberCountryCode.setEnabled(false);
        
        jTextFieldMobileNum.setEnabled(false);

        jButtonCheckOTP.setEnabled(false);
        jTextFieldEnterOTP.setEnabled(false);
        jButtonCheckOTP.setEnabled(false);

        jTextFieldNewPassword.setEnabled(false);
        jTextConfirmPassword.setEnabled(false);
        jButtonResetPassword.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonSelectEmailActionPerformed

    private void jRadioButtonSelectMobileNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSelectMobileNumberActionPerformed
        // TODO add your handling code here:
        jTextFieldMobileNum.setEnabled(true);
        jRadioButtonSelectEmail.setEnabled(true);
        
         jButtonSendOTP.setEnabled(true);
        jLabelEmailIdCheck.setText("");
        jLabelPhoneNumberCheck.setText("");
        
        jTextFieldMobileNumberCountryCode.setEnabled(false);
        jRadioButtonSelectEmail.setEnabled(true);
        jRadioButtonSelectMobileNumber.setEnabled(true);
        
        jTextFieldEmailId.setEnabled(false);
        jButtonCheckOTP.setEnabled(false);
        jTextFieldEnterOTP.setEnabled(false);
        jButtonCheckOTP.setEnabled(false);

        jTextFieldNewPassword.setEnabled(false);
        jTextConfirmPassword.setEnabled(false);
        jButtonResetPassword.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonSelectMobileNumberActionPerformed

    private void jButtonCheckUserName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckUserName1ActionPerformed
        // TODO add your handling code here:
        jLabelUsernameCheck.setText("");
        jTextFieldMobileNum.setEnabled(false);
        jButtonSendOTP.setEnabled(false);
        jLabelEmailIdCheck.setText("");
        jLabelPhoneNumberCheck.setText("");
        
        jTextFieldMobileNumberCountryCode.setEnabled(false);
        jRadioButtonSelectEmail.setEnabled(false);
        jRadioButtonSelectMobileNumber.setEnabled(false);
        
        jTextFieldEmailId.setEnabled(false);
        jButtonCheckOTP.setEnabled(false);
        jTextFieldEnterOTP.setEnabled(false);
        jButtonCheckOTP.setEnabled(false);

        jTextFieldNewPassword.setEnabled(false);
        jTextConfirmPassword.setEnabled(false);
        jButtonResetPassword.setEnabled(false);
        
        String userName = jTextFieldUserName.getText();
        boolean error = fieldsValidator.validate(jTextFieldUserName);
        
        if (error) {
            setNotVerifiedLabel(jLabelUsernameCheck);
            return;
        }
        
        Person person = ecoSystem.globalUserDirectory.get(userName);
        if (person == null) {
            setNotVerifiedLabel(jLabelUsernameCheck);
            return;
        }
        
        selectedPerson = person;
        
        setVerifiedLabel(jLabelUsernameCheck);
        
        jRadioButtonSelectEmail.setEnabled(true);
        jRadioButtonSelectMobileNumber.setEnabled(true);
        jButtonSendOTP.setEnabled(true);
    }//GEN-LAST:event_jButtonCheckUserName1ActionPerformed

    private void jButtonSendOTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendOTPActionPerformed
        // TODO add your handling code here:
        
        if (jRadioButtonSelectEmail.isSelected()) {
            boolean error = fieldsValidator.validateEmail(jTextFieldEmailId);
            boolean verifiedEmail = jTextFieldEmailId.getText().equals(selectedPerson.getPersonDetails().getEmailId());
            if (error || !verifiedEmail) {
                setNotVerifiedLabel(jLabelEmailIdCheck);
                return;
            }
            setVerifiedLabel(jLabelEmailIdCheck);
            jTextFieldEnterOTP.setEnabled(true);
            jButtonCheckOTP.setEnabled(true);
            sendOTPViaEmail();
            return;
        }
        
        if (jRadioButtonSelectMobileNumber.isSelected()) {
            boolean error = fieldsValidator.validate(jTextFieldMobileNum, 10);
            String phoneNumber = jTextFieldMobileNum.getText();
            boolean verifiedPhone = phoneNumber.equals(selectedPerson.getPersonDetails().getPhoneNumber());
            if (error || !verifiedPhone) {
                setNotVerifiedLabel(jLabelPhoneNumberCheck);
                return;
            }
            setVerifiedLabel(jLabelPhoneNumberCheck);
            jTextFieldEnterOTP.setEnabled(true);
            jButtonCheckOTP.setEnabled(true);
            sendOTPViaTextMessage();
            return;
        }
        
        JOptionPane.showMessageDialog(null, "Select either email or mobile option to send OTP");
    }//GEN-LAST:event_jButtonSendOTPActionPerformed

    private void jButtonCheckOTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckOTPActionPerformed
        // TODO add your handling code here:
        
        String enteredOTP = jTextFieldEnterOTP.getText();
        if (!sentOtp.equals(enteredOTP)) {
            setNotVerifiedLabel(jLabelOTPCheck);
            return;
        } else {
            setVerifiedLabel(jLabelOTPCheck);
            jTextFieldNewPassword.setEnabled(true);
            jTextConfirmPassword.setEnabled(true);
            jButtonResetPassword.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonCheckOTPActionPerformed

    private void jButtonResetPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetPasswordActionPerformed
        // TODO add your handling code here:
        
        String enteredPassword = new String(jTextFieldNewPassword.getPassword());
        String confirmPassword = new String(jTextConfirmPassword.getPassword());
        System.out.println("enteredPassword = " + enteredPassword + "   confirmPassword = " + confirmPassword);
        if (StringUtils.isBlank(enteredPassword) || 
                StringUtils.isBlank(confirmPassword) ||
                !enteredPassword.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(null, "Password mismatch. Try again");
            return;
        }
        
        
        selectedPerson.getPersonDetails().setPassword(enteredPassword);
        ecoSystem.globalUserDirectory.updateUser(selectedPerson);
        disableAllButtons();
        JOptionPane.showMessageDialog(null, "Password successfully updated");
        disableAllButtons();
        sendPasswordUpdateEmail();
    }//GEN-LAST:event_jButtonResetPasswordActionPerformed

    void disableAllButtons() {
        jTextFieldMobileNumberCountryCode.setEnabled(false);
        jRadioButtonSelectEmail.setEnabled(false);
        jRadioButtonSelectMobileNumber.setEnabled(false);
        
        jTextFieldUserName.setEnabled(false);
        jButtonCheckUserName1.setEnabled(false);
        jTextFieldEmailId.setEnabled(false);
        jTextFieldMobileNum.setEnabled(false);
        jButtonSendOTP.setEnabled(false);
        jButtonCheckOTP.setEnabled(false);
        jTextFieldEnterOTP.setEnabled(false);
        jButtonCheckOTP.setEnabled(false);

        jTextFieldNewPassword.setEnabled(false);
        jTextConfirmPassword.setEnabled(false);
        jButtonResetPassword.setEnabled(false);
    }
    
    void sendPasswordUpdateEmail() {
       boolean success = new EmailClient().sendEmail(
               selectedPerson.getPersonDetails().getEmailId(), 
               ecoSystem.getSysAdminEmail(), 
               ecoSystem.getSysAdmingEmailPassword(), 
               "Password successfully reset for Health Springs App", 
               getPassWordSuccessfullResetMessage());
    }
    
    String getPassWordSuccessfullResetMessage() {
        Date date = Date.from(Instant.now());
        return "Hi " + selectedPerson.getPersonDetails().getFullName() + "!\n" +
                "This is to inform you that your password has been successfully updated on " + date.toString() + " PST.\n" +
                "\n\n\n" +
                "Thank you,\n" + 
                "Health Springs App Team";
    }
    
    void setVerifiedLabel(JLabel label) {
        label.setText("Verified!");
        label.setForeground(Color.green);
    }
    
    void setNotVerifiedLabel(JLabel label) {
        label.setText("Unable to verify. Try again.");
        label.setForeground(Color.red);
    }
    
    void sendOTPViaEmail() {
      sentOtp = getRandomOPT();
       boolean success = new EmailClient().sendEmail(
               selectedPerson.getPersonDetails().getEmailId(), 
               ecoSystem.getSysAdminEmail(), 
               ecoSystem.getSysAdmingEmailPassword(), 
               "Password Reset for Health Springs App", 
               getPassWordResetMessage(sentOtp));
    }
    
    String getPassWordResetMessage(String otp) {
        return "Hi " + selectedPerson.getPersonDetails().getFullName() + "!\n" +
                "Your 6 digit OPT to reset password is : " + otp + "\n" +
                "Please visit your app and enter the code to reset the password." + 
                "\n\n\n" +
                "Thank you,\n" + 
                "Health Springs App Team";
    }
    
    void sendOTPViaTextMessage() {
        sentOtp = getRandomOPT();
        new SMSSender().sendSMSAsynchronous(selectedPerson.getPersonDetails().getPhoneNumber(), getPassWordResetMessage(sentOtp));
    }
    
    String getRandomOPT() {
        int number = rnd.nextInt(999999);
        // this will convert any number sequence into 6 character.
        return String.format("%06d", number);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonCheckOTP;
    private javax.swing.JButton jButtonCheckUserName1;
    private javax.swing.JButton jButtonResetPassword;
    private javax.swing.JButton jButtonSendOTP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelEmailIdCheck;
    private javax.swing.JLabel jLabelOTPCheck;
    private javax.swing.JLabel jLabelPhoneNumberCheck;
    private javax.swing.JLabel jLabelUsernameCheck;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonSelectEmail;
    private javax.swing.JRadioButton jRadioButtonSelectMobileNumber;
    private javax.swing.JPasswordField jTextConfirmPassword;
    private javax.swing.JTextField jTextFieldEmailId;
    private javax.swing.JTextField jTextFieldEnterOTP;
    private javax.swing.JTextField jTextFieldMobileNum;
    private javax.swing.JTextField jTextFieldMobileNumberCountryCode;
    private javax.swing.JPasswordField jTextFieldNewPassword;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables
}
