/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Utils;

import Personnel.Person;
import java.awt.Image;
import java.time.LocalDate;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author mrs.katey
 */
public class RatingsJPanel extends javax.swing.JPanel {

    Person person;
    LocalDate ratingsDate;
    ConsoleLogger log = ConsoleLogger.getLogger();
    Rating rating;
    
    RatingsJPanel(Person person, Rating rating, LocalDate ratingsDate) {
        initComponents();
        initizlizeRatingIcons();
        initializeRadioButtonGroup();
        this.person = person;
        this.ratingsDate = ratingsDate;
        this.rating = rating;
    }
    
    void setStarIcons(JLabel label, String iconPath) {
        ImageIcon imageIcon = new ImageIcon(getClass().getResource(iconPath));
        Image image = imageIcon.getImage(); // transform it 
        Image newimg = image.getScaledInstance(100, 100,  java.awt.Image.SCALE_SMOOTH);
        imageIcon = new ImageIcon(newimg);  // transform it back]
        label.setIcon(imageIcon);
    }
    
    void initizlizeRatingIcons() {
        setStarIcons(jLabel1Star, "/images_icons/icon-1-star.png");
        setStarIcons(jLabel2Star, "/images_icons/icon-2-star.png");
        setStarIcons(jLabel3Star, "/images_icons/icon-3-star.png");
        setStarIcons(jLabel4Star, "/images_icons/icon-4-star.png");
        setStarIcons(jLabel5Star, "/images_icons/icon-5-star.png");
    }
    
    private void disableControls() {
        jRadioButton1Star.setEnabled(false);
        jRadioButton2Star.setEnabled(false);
        jRadioButton3Star.setEnabled(false);
        jRadioButton4Star.setEnabled(false);
        jRadioButton5Star.setEnabled(false);
        jTextAreaFeedbackText.setEnabled(false);
        jButtonSubmitReview.setEnabled(false);
    }
    
    private void initializeRadioButtonGroup() {
        this.radioButtonGroup.add(jRadioButton1Star);
        this.radioButtonGroup.add(jRadioButton2Star);
        this.radioButtonGroup.add(jRadioButton3Star);
        this.radioButtonGroup.add(jRadioButton4Star);
        this.radioButtonGroup.add(jRadioButton5Star);
    }
    
    private int getSelectedRating() {
        if (jRadioButton1Star.isSelected()) {
            return 1;
        }
        if (jRadioButton2Star.isSelected()) {
            return 2;
        }
        if (jRadioButton3Star.isSelected()) {
            return 3;
        }
        if (jRadioButton4Star.isSelected()) {
            return 4;
        }
        if (jRadioButton5Star.isSelected()) {
            return 5;
        }
        return -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jRadioButton5Star = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton4Star = new javax.swing.JRadioButton();
        jRadioButton3Star = new javax.swing.JRadioButton();
        jRadioButton2Star = new javax.swing.JRadioButton();
        jRadioButton1Star = new javax.swing.JRadioButton();
        jLabel3Star = new javax.swing.JLabel();
        jLabel4Star = new javax.swing.JLabel();
        jLabel1Star = new javax.swing.JLabel();
        jLabel2Star = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaFeedbackText = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButtonSubmitReview = new javax.swing.JButton();
        jLabel5Star = new javax.swing.JLabel();

        jRadioButton5Star.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jRadioButton5Star.setForeground(new java.awt.Color(0, 204, 102));
        jRadioButton5Star.setText("Very Satisfied");
        jRadioButton5Star.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5StarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        jLabel1.setText("Sumbit Review");

        jRadioButton4Star.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jRadioButton4Star.setForeground(new java.awt.Color(102, 204, 0));
        jRadioButton4Star.setText("Somewhat Satisfied");

        jRadioButton3Star.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jRadioButton3Star.setForeground(new java.awt.Color(153, 153, 0));
        jRadioButton3Star.setText("Neither satisfied nor dissatisfied");

        jRadioButton2Star.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jRadioButton2Star.setForeground(new java.awt.Color(255, 102, 102));
        jRadioButton2Star.setText("Somewhat dissatisfied");

        jRadioButton1Star.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jRadioButton1Star.setForeground(new java.awt.Color(204, 51, 0));
        jRadioButton1Star.setText("Very dissatisfied");

        jLabel3Star.setIcon(new javax.swing.ImageIcon("/Users/mrs.katey/Desktop/example-3-star-icon.png")); // NOI18N

        jLabel4Star.setIcon(new javax.swing.ImageIcon("/Users/mrs.katey/Desktop/example-3-star-icon.png")); // NOI18N

        jLabel1Star.setIcon(new javax.swing.ImageIcon("/Users/mrs.katey/Desktop/example-3-star-icon.png")); // NOI18N

        jLabel2Star.setIcon(new javax.swing.ImageIcon("/Users/mrs.katey/Desktop/example-3-star-icon.png")); // NOI18N

        jTextAreaFeedbackText.setColumns(20);
        jTextAreaFeedbackText.setRows(5);
        jScrollPane1.setViewportView(jTextAreaFeedbackText);

        jLabel3.setText("Optional Feedback");

        jButtonSubmitReview.setText("Submit Review");
        jButtonSubmitReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitReviewActionPerformed(evt);
            }
        });

        jLabel5Star.setIcon(new javax.swing.ImageIcon("/Users/mrs.katey/Desktop/example-3-star-icon.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonSubmitReview, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(266, 266, 266))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(193, 193, 193)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButton4Star)
                                        .addComponent(jRadioButton3Star)
                                        .addComponent(jRadioButton2Star)
                                        .addComponent(jRadioButton1Star)
                                        .addComponent(jRadioButton5Star))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(3, 3, 3)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1Star)
                                                .addComponent(jLabel2Star)))
                                        .addComponent(jLabel3Star)
                                        .addComponent(jLabel5Star)
                                        .addComponent(jLabel4Star)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(203, 203, 203)
                                    .addComponent(jLabel3)))
                            .addGap(309, 309, 309)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jRadioButton5Star))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5Star, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton4Star)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4Star, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton3Star)
                        .addGap(16, 16, 16)
                        .addComponent(jRadioButton2Star))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3Star, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2Star, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1Star, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1Star))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addComponent(jButtonSubmitReview, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton5StarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5StarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5StarActionPerformed

    private void jButtonSubmitReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitReviewActionPerformed
        // TODO add your handling code here:
        int selectedRating = getSelectedRating();
        if (selectedRating == -1) {
            JOptionPane.showMessageDialog(jPanel1, "Please select a rating");
            log.error("Please select a rating");
            return;
        }
        
        String feedBack = jTextAreaFeedbackText.getText();
        rating.setRating(selectedRating);
        rating.setFeedBack(feedBack);
        rating.setRatingDate(ratingsDate);
        rating.setStatus(Rating.RatingStatus.RATING_PROVIDED);
        person.addRating(rating);
        log.error("Ratings provided");
        jButtonSubmitReview.setText("Thank you! Your review has been sumbitted!");
        disableControls();
    }//GEN-LAST:event_jButtonSubmitReviewActionPerformed

    ButtonGroup radioButtonGroup = new ButtonGroup();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSubmitReview;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1Star;
    private javax.swing.JLabel jLabel2Star;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3Star;
    private javax.swing.JLabel jLabel4Star;
    private javax.swing.JLabel jLabel5Star;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1Star;
    private javax.swing.JRadioButton jRadioButton2Star;
    private javax.swing.JRadioButton jRadioButton3Star;
    private javax.swing.JRadioButton jRadioButton4Star;
    private javax.swing.JRadioButton jRadioButton5Star;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaFeedbackText;
    // End of variables declaration//GEN-END:variables
}
